/**
 * Mock data for Vismaya Admin Dashboard
 * Centralized data store for all Admin operations.
 */

export const initialTalents = [
  {
    id: "tal-901",
    name: "Aarav Mehra",
    stageName: "Aarav Mehra",
    city: "Mumbai",
    state: "Maharashtra",
    age: 24,
    dob: "2002-05-14",
    gender: "Male",
    category: "Actor / Model",
    joinedDate: "2026-09-28",
    status: "Pending",
    email: "aarav.mehra@gmail.com",
    phone: "+91 98192 34567",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    physical: {
      height: "5'11\" (180 cm)",
      weight: "72 kg",
      skinTone: "Fair / Wheatish",
      hairColor: "Black",
      eyeColor: "Dark Brown",
      bodyType: "Athletic / Lean",
      chest: "39\"",
      waist: "31\"",
      shoeSize: "UK 9",
    },
    skills: ["Screen Acting", "Method Acting", "Martial Arts (Taekwondo)", "Guitar", "Voice Over", "Bike Stunts"],
    languages: ["Hindi (Native)", "English (Fluent)", "Punjabi (Conversational)"],
    experience: [
      {
        id: "exp-101",
        role: "Supporting Lead (Kabir)",
        project: "Amazon miniTV Series 'Campus Beats'",
        production: "Banijay Asia",
        year: "2025",
        type: "OTT Series",
      },
      {
        id: "exp-102",
        role: "Protagonist",
        project: "Campus Story Short Film",
        production: "FTII Pune",
        year: "2024",
        type: "Short Film",
      },
    ],
    portfolio: [
      { id: "pf-1", title: "Primary Headshot", type: "Photo", url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80" },
      { id: "pf-2", title: "Full Body Profile", type: "Photo", url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80" },
      { id: "pf-3", title: "Commercial Showreel 2026", type: "Video", url: "https://www.w3schools.com/html/mov_bbb.mp4" },
    ],
    bio: "FTII trained screen actor with theater roots in Prithvi Theatre. Seeking gritty OTT roles, character leads, and high-impact commercial campaigns.",
    statusReason: null,
  },
  {
    id: "tal-902",
    name: "Ananya Deshmukh",
    stageName: "Ananya D",
    city: "Pune",
    state: "Maharashtra",
    age: 15,
    dob: "2011-08-20",
    gender: "Female",
    category: "Child Artist",
    joinedDate: "2026-09-29",
    status: "Pending",
    email: "deshmukh.family@gmail.com",
    phone: "+91 97654 12389",
    avatar: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=300&auto=format&fit=crop&q=80",
    physical: {
      height: "5'1\" (155 cm)",
      weight: "43 kg",
      skinTone: "Fair",
      hairColor: "Dark Brown",
      eyeColor: "Black",
      bodyType: "Petite",
      shoeSize: "UK 5",
    },
    skills: ["Classical Bharatanatyam", "Expressive Monologue", "Singing (Hindustani Classical)", "Skating"],
    languages: ["Marathi (Native)", "Hindi (Fluent)", "English (Fluent)"],
    experience: [
      {
        id: "exp-201",
        role: "Younger Sister",
        project: "Horlicks TVC National Campaign",
        production: "Ogilvy India",
        year: "2025",
        type: "TVC Ad",
      },
    ],
    portfolio: [
      { id: "pf-4", title: "Studio Headshot", type: "Photo", url: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80" },
      { id: "pf-5", title: "Audition Self-Tape (Emotional)", type: "Video", url: "https://www.w3schools.com/html/mov_bbb.mp4" },
    ],
    bio: "Child artist & classical dancer with natural expressions. Father manages schedules.",
    guardianConsent: {
      isMinor: true,
      guardianName: "Suresh Deshmukh (Father)",
      guardianPhone: "+91 97654 12389",
      guardianEmail: "suresh.deshmukh@gmail.com",
      consentLetterUploaded: true,
      aadhaarVerified: true,
      notes: "Signed NOC for shoot hours adhering to child labor guidelines.",
    },
    statusReason: null,
  },
  {
    id: "tal-904",
    name: "Riya Sharma",
    stageName: "Riya Sharma",
    city: "Mumbai",
    state: "Maharashtra",
    age: 22,
    dob: "2004-04-12",
    gender: "Female",
    category: "Actor / Model",
    joinedDate: "2026-08-15",
    status: "Approved",
    email: "riya.sharma@vismaya.io",
    phone: "+91 98765 43210",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    physical: {
      height: "5'6\" (168 cm)",
      weight: "54 kg",
      skinTone: "Wheatish",
      hairColor: "Dark Brown",
      eyeColor: "Hazel Brown",
      bodyType: "Slim / Athletic",
      chest: "34\"",
      waist: "26\"",
      hips: "36\"",
      shoeSize: "UK 6",
    },
    skills: ["Method Acting", "Kathak Dance", "Voice Over", "Horse Riding", "Stage Combat", "Improvisation"],
    languages: ["Hindi (Native)", "English (Fluent)", "Marathi (Fluent)", "Gujarati (Conversational)"],
    experience: [
      {
        id: "exp-301",
        role: "Protagonist (Nisha)",
        project: "Short Film 'Awaaz' (MUBI)",
        production: "Whistling Woods",
        year: "2025",
        type: "Film",
      },
      {
        id: "exp-302",
        role: "Supporting Lead",
        project: "Tanishq Festive Digital Campaign",
        production: "Famous Studios",
        year: "2024",
        type: "Advertisement",
      },
    ],
    portfolio: [
      { id: "pf-6", title: "Commercial Headshot", type: "Photo", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80" },
      { id: "pf-7", title: "Kathak Monologue Reel", type: "Video", url: "https://www.w3schools.com/html/mov_bbb.mp4" },
    ],
    bio: "Barry John Acting Studio alumni with 3+ years in Marathi/Hindi short films & brand campaigns.",
    statusReason: null,
  },
  {
    id: "tal-905",
    name: "Kabir Roy",
    stageName: "Kabir Roy",
    city: "Kolkata",
    state: "West Bengal",
    age: 28,
    dob: "1998-02-19",
    gender: "Male",
    category: "Actor",
    joinedDate: "2026-08-10",
    status: "Approved",
    email: "kabir.roy@gmail.com",
    phone: "+91 98300 87654",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    physical: {
      height: "6'0\" (183 cm)",
      weight: "78 kg",
      skinTone: "Fair",
      hairColor: "Black",
      eyeColor: "Black",
      bodyType: "Muscular",
      chest: "41\"",
      waist: "32\"",
      shoeSize: "UK 10",
    },
    skills: ["Intense Drama", "Bengali & Hindi Diction", "Physical Theater", "Swimming"],
    languages: ["Bengali (Native)", "Hindi (Fluent)", "English (Fluent)"],
    experience: [
      {
        id: "exp-401",
        role: "Antagonist (Bikram)",
        project: "Hoichoi Thriller 'Chhaya'",
        production: "SVF Entertainment",
        year: "2025",
        type: "Web Series",
      },
    ],
    portfolio: [
      { id: "pf-8", title: "Intense Character Look", type: "Photo", url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80" },
    ],
    bio: "Bengali theater artist with 5+ years experience transitioning into Pan-India OTT series.",
    statusReason: null,
  },
  {
    id: "tal-906",
    name: "Tara Nair",
    stageName: "Tara Nair",
    city: "Bangalore",
    state: "Karnataka",
    age: 23,
    dob: "2003-11-04",
    gender: "Female",
    category: "Dancer / Actor",
    joinedDate: "2026-09-15",
    status: "Rejected",
    email: "tara.nair@outlook.com",
    phone: "+91 99450 67890",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80",
    physical: {
      height: "5'5\" (165 cm)",
      weight: "51 kg",
      skinTone: "Dusky",
      hairColor: "Black",
      eyeColor: "Dark Brown",
      bodyType: "Flexible / Dancer",
      shoeSize: "UK 6",
    },
    skills: ["Contemporary Dance", "Mohiniyattam", "Yoga"],
    languages: ["Malayalam (Native)", "English (Fluent)", "Hindi (Basic)"],
    experience: [],
    portfolio: [],
    bio: "Dancer looking for background dance roles.",
    statusReason: "Low resolution blurry photos uploaded. Incomplete past training background.",
  },
  {
    id: "tal-907",
    name: "Vikram Chauhan",
    stageName: "Vikram Chauhan",
    city: "Delhi",
    state: "Delhi NCR",
    age: 31,
    dob: "1995-07-11",
    gender: "Male",
    category: "Actor / Voice Artist",
    joinedDate: "2026-07-20",
    status: "Suspended",
    email: "vikram.chauhan@gmail.com",
    phone: "+91 98111 23456",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    physical: {
      height: "5'10\" (178 cm)",
      weight: "75 kg",
      skinTone: "Wheatish",
      hairColor: "Black",
      eyeColor: "Brown",
      bodyType: "Average",
      shoeSize: "UK 8",
    },
    skills: ["Voice Modulation", "Dubbing", "Hindi Dialects (Haryanvi, UP)", "Stand-up Comedy"],
    languages: ["Hindi (Native)", "English (Fluent)", "Punjabi"],
    experience: [
      {
        id: "exp-501",
        role: "Voice Lead",
        project: "Animated Series 'Veer'",
        production: "Green Gold",
        year: "2024",
        type: "Animation Voice",
      },
    ],
    portfolio: [],
    bio: "Voice artist & stage actor.",
    statusReason: "Repeated no-show at scheduled offline audition tests coordinated by Vismaya Casting Desk.",
  },
];

export const initialRecruiters = [
  {
    id: "rec-201",
    company: "Zee Films",
    contactPerson: "Vikram Malhotra",
    type: "Production House",
    city: "Mumbai",
    state: "Maharashtra",
    joinedDate: "2026-08-15",
    status: "Verified",
    email: "vikram.malhotra@zeefilms.com",
    phone: "+91 98201 54321",
    website: "https://zeefilms.com",
    gstNumber: "27AAACZ1234F1Z8",
    regNumber: "CIN: U92100MH1992PLC068301",
    requirementsCount: 3,
    avatar: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=300&auto=format&fit=crop&q=80",
    description: "Leading Bollywood and Pan-India feature film & high-budget OTT production studio.",
    verificationDocs: [
      { id: "doc-1", title: "Certificate of Incorporation (MCA)", verified: true, type: "PDF" },
      { id: "doc-2", title: "GST Registration Certificate", verified: true, type: "PDF" },
      { id: "doc-3", title: "Letter of Authority for Casting Head", verified: true, type: "PDF" },
    ],
    statusReason: "Corporate CIN and GST registration credentials verified by Vismaya Compliance Desk.",
  },
  {
    id: "rec-202",
    company: "Ogilvy Creative Labs",
    contactPerson: "Priya Sundaram",
    type: "Ad Agency",
    city: "Mumbai",
    state: "Maharashtra",
    joinedDate: "2026-09-27",
    status: "Pending",
    email: "priya.sundaram@ogilvy.com",
    phone: "+91 98200 98765",
    website: "https://ogilvy.com/in",
    gstNumber: "27AAAC05678B1ZG",
    regNumber: "CIN: U74300MH1985PTC035412",
    requirementsCount: 1,
    avatar: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=300&auto=format&fit=crop&q=80",
    description: "Award-winning global advertising and commercial campaign agency producing TVCs & digital ads.",
    verificationDocs: [
      { id: "doc-4", title: "GST Certificate.pdf", verified: false, type: "PDF" },
      { id: "doc-5", title: "Agency Agency Deck & PAN.pdf", verified: false, type: "PDF" },
    ],
    statusReason: null,
  },
  {
    id: "rec-203",
    company: "Mukesh Casting Studio",
    contactPerson: "Karan Johar",
    type: "Casting Agency",
    city: "Mumbai",
    state: "Maharashtra",
    joinedDate: "2026-09-29",
    status: "Pending",
    email: "karan@mukeshcasting.in",
    phone: "+91 98922 11223",
    website: "https://mukeshcasting.in",
    gstNumber: "27BBBPM9988C1Z2",
    regNumber: "MSME: UDYAM-MH-19-0029381",
    requirementsCount: 0,
    avatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=300&auto=format&fit=crop&q=80",
    description: "Boutique casting agency specializing in independent cinema, web shorts, and theater casting.",
    verificationDocs: [
      { id: "doc-6", title: "MSME Registration Certificate", verified: false, type: "PDF" },
    ],
    statusReason: null,
  },
  {
    id: "rec-204",
    company: "Sun NXT Originals",
    contactPerson: "Senthil Kumar",
    type: "OTT Platform",
    city: "Hyderabad",
    state: "Telangana",
    joinedDate: "2026-08-01",
    status: "Verified",
    email: "senthil@sunnetwork.in",
    phone: "+91 94440 55667",
    website: "https://sunnxt.net",
    gstNumber: "36AAACS7766K1Z9",
    regNumber: "CIN: L32100TN1985PLC012809",
    requirementsCount: 2,
    avatar: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=300&auto=format&fit=crop&q=80",
    description: "Regional powerhouse producing multilingual South Indian thrillers and family dramas.",
    verificationDocs: [
      { id: "doc-7", title: "CIN Certificate & Board Resolution", verified: true, type: "PDF" },
    ],
    statusReason: "Verified corporate OTT division credentials.",
  },
  {
    id: "rec-205",
    company: "Apex Media Talent Hub",
    contactPerson: "Rajiv Singhania",
    type: "Casting Agency",
    city: "Delhi",
    state: "Delhi NCR",
    joinedDate: "2026-09-10",
    status: "Rejected",
    email: "singhania@apexmedia.org",
    phone: "+91 98100 44556",
    website: "https://apexmediahub.fake",
    gstNumber: "07AAXPA1234F1Z0",
    regNumber: "INVALID-REG-892",
    requirementsCount: 0,
    avatar: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&auto=format&fit=crop&q=80",
    description: "Freelance production setup.",
    verificationDocs: [
      { id: "doc-8", title: "Invalid_tax_doc.pdf", verified: false, type: "PDF" },
    ],
    statusReason: "Unverifiable GST number and fake business address provided during verification check.",
  },
  {
    id: "rec-206",
    company: "Starlet Media House",
    contactPerson: "Dinesh Agarwal",
    type: "Production House",
    city: "Bangalore",
    state: "Karnataka",
    joinedDate: "2026-07-15",
    status: "Suspended",
    email: "dinesh@starletmedia.com",
    phone: "+91 98450 33221",
    website: "https://starletmedia.com",
    gstNumber: "29AABCS8899D1ZZ",
    regNumber: "CIN: U22100KA2015PTC078901",
    requirementsCount: 1,
    avatar: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=300&auto=format&fit=crop&q=80",
    description: "Commercials and regional digital campaigns.",
    verificationDocs: [
      { id: "doc-9", title: "Starlet_CIN.pdf", verified: true, type: "PDF" },
    ],
    statusReason: "Violated terms of service by attempting direct unmediated contact with registered talent.",
  },
];

export const initialMediaQueue = [
  {
    id: "med-501",
    talentId: "tal-901",
    talentName: "Aarav Mehra",
    talentCategory: "Actor",
    type: "photo",
    title: "Primary Studio Headshot (Commercial)",
    category: "Commercial Headshot",
    uploadDate: "2026-09-30",
    url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1000&auto=format&fit=crop&q=80",
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    fileSize: "3.4 MB",
    dimensions: "2400 x 3200 px",
    status: "Pending",
    statusReason: null,
  },
  {
    id: "med-502",
    talentId: "tal-901",
    talentName: "Aarav Mehra",
    talentCategory: "Actor",
    type: "video",
    title: "Action & Drama Monologue Audition Reel",
    category: "Audition Reel",
    uploadDate: "2026-09-30",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    duration: "1m 45s",
    fileSize: "28.1 MB",
    status: "Pending",
    statusReason: null,
  },
  {
    id: "med-503",
    talentId: "tal-902",
    talentName: "Ananya Deshmukh",
    talentCategory: "Child Artist",
    type: "photo",
    title: "Full Length Classical Dance Look",
    category: "Costume Look",
    uploadDate: "2026-09-29",
    url: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=1000&auto=format&fit=crop&q=80",
    thumbnail: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&auto=format&fit=crop&q=80",
    fileSize: "2.8 MB",
    dimensions: "1800 x 2700 px",
    status: "Pending",
    statusReason: null,
  },
  {
    id: "med-504",
    talentId: "tal-905",
    talentName: "Kabir Roy",
    talentCategory: "Actor",
    type: "showreel",
    title: "Bengali Theater & Monologue Highlights",
    category: "Showreel",
    uploadDate: "2026-09-28",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    duration: "2m 10s",
    fileSize: "44.6 MB",
    status: "Pending",
    statusReason: null,
  },
  {
    id: "med-505",
    talentId: "tal-904",
    talentName: "Riya Sharma",
    talentCategory: "Actor",
    type: "photo",
    title: "Profile Lookbook - Editorial 2026",
    category: "Lookbook",
    uploadDate: "2026-09-20",
    url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1000&auto=format&fit=crop&q=80",
    thumbnail: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    fileSize: "4.1 MB",
    dimensions: "3000 x 4000 px",
    status: "Approved",
    statusReason: null,
  },
  {
    id: "med-506",
    talentId: "tal-906",
    talentName: "Tara Nair",
    talentCategory: "Dancer",
    type: "photo",
    title: "Low Light Selfie comp-card",
    category: "Headshot",
    uploadDate: "2026-09-15",
    url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1000&auto=format&fit=crop&q=80",
    thumbnail: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80",
    fileSize: "800 KB",
    dimensions: "720 x 1280 px",
    status: "Rejected",
    statusReason: "Blurry image with heavy compression filters. High resolution natural light headshots required.",
  },
];

export const initialRequirementRequests = [
  {
    id: "req-101",
    projectTitle: "Mumbai Diaries Season 2",
    recruiterId: "rec-201",
    recruiterName: "Vikram Malhotra",
    company: "Zee Films",
    projectType: "OTT Series",
    budget: "₹45,000 - ₹80,000 / day",
    budgetType: "Paid",
    submittedDate: "2026-09-12",
    status: "Published",
    description: "Critically acclaimed medical drama series returning for Season 2. Seeking talented lead and supporting artists for high-intensity hospital and investigative storylines.",
    locations: "Mumbai & Pune Studios",
    shootStartDate: "2026-11-10",
    shootEndDate: "2027-01-20",
    deadline: "2026-10-15",
    requiredMaterials: [
      "Commercial Headshot",
      "Full Body Look",
      "Dramatic Video Showreel",
      "Audition Monologue Self-Tape",
    ],
    roles: [
      {
        id: "r-1",
        roleName: "Dr. Tanya Roy (Trauma Specialist)",
        artistsCount: 1,
        ageRange: "21 - 27 years",
        gender: "Female",
        look: "Sharp, intelligent, urban contemporary look",
        language: "Hindi (Fluent), English (Fluent)",
        skills: "Fast dialogue delivery, emotional control",
        notes: "Key role across 6 episodes.",
      },
      {
        id: "r-2",
        roleName: "Rohan Varma (Investigative Reporter)",
        artistsCount: 1,
        ageRange: "24 - 30 years",
        gender: "Male",
        look: "Intense, expressive eyes, rugged style",
        language: "Hindi, English",
        skills: "Voice modulation, high-stress scenes",
        notes: "Requires monologue test.",
      },
    ],
    clarificationNotes: [
      {
        id: "nt-1",
        author: "Admin (Sanjay)",
        time: "14 Sep 2026, 11:30 AM",
        text: "Called recruiter Vikram Malhotra. Confirmed character age window 21-27 for Dr. Tanya Roy and daily budget ₹60,000 baseline with accommodation in Mumbai.",
      },
      {
        id: "nt-2",
        author: "Admin (Pooja)",
        time: "15 Sep 2026, 03:15 PM",
        text: "Verified shoot dates 10 Nov 2026 to 20 Jan 2027. Ready to publish as public casting call.",
      },
    ],
    statusReason: null,
  },
  {
    id: "req-102",
    projectTitle: "Glow Skincare National TVC",
    recruiterId: "rec-201",
    recruiterName: "Vikram Malhotra",
    company: "Zee Films",
    projectType: "Commercial / TVC",
    budget: "₹1,50,000 lump sum",
    budgetType: "Paid",
    submittedDate: "2026-09-18",
    status: "Ready to Publish",
    description: "Premium commercial TVC & digital campaign for a luxury botanical skincare range. Focusing on close-up skin radiance and natural expressions.",
    locations: "Mumbai (Famous Studios)",
    shootStartDate: "2026-10-24",
    shootEndDate: "2026-10-26",
    deadline: "2026-10-06",
    requiredMaterials: ["Commercial Headshot", "Full Body Look", "Audition Monologue Self-Tape"],
    roles: [
      {
        id: "r-3",
        roleName: "Lead Female Face (Natural Radiance)",
        artistsCount: 2,
        ageRange: "20 - 26 years",
        gender: "Female",
        look: "Photogenic smile, natural skin tone, expressive eyes",
        language: "Hindi",
        skills: "Camera ease, subtle facial reactions",
        notes: "Macro beauty lighting shots.",
      },
    ],
    clarificationNotes: [
      {
        id: "nt-3",
        author: "Admin (Sanjay)",
        time: "20 Sep 2026, 04:00 PM",
        text: "Phone call on 20 Sep: Recruiter confirmed lump sum ₹1,50,000 for 2 shoot days with digital usage buyout rights for 1 year.",
      },
    ],
    statusReason: null,
  },
  {
    id: "req-103",
    projectTitle: "Period Historical Feature Film 'Samrat'",
    recruiterId: "rec-201",
    recruiterName: "Vikram Malhotra",
    company: "Zee Films",
    projectType: "Feature Film",
    budget: "₹3,00,000 + Outstation Travel & Stay",
    budgetType: "Travel + Stay",
    submittedDate: "2026-09-25",
    status: "Needs Clarification",
    description: "Grand historical theatrical feature film exploring royal classical arts of 16th-century India.",
    locations: "Jaipur Heritage Palaces & Film City",
    shootStartDate: "2026-12-01",
    shootEndDate: "2027-02-28",
    deadline: "2026-10-20",
    requiredMaterials: ["Commercial Headshot", "Dramatic Video Showreel", "Audition Monologue Self-Tape"],
    roles: [
      {
        id: "r-4",
        roleName: "Priyamvada (Court Classical Dancer)",
        artistsCount: 1,
        ageRange: "20 - 26 years",
        gender: "Female",
        look: "Classical Indian features, graceful posture",
        language: "Hindi & Urdu diction",
        skills: "Classical dance (Kathak mandatory)",
        notes: "Choreography test side included.",
      },
    ],
    clarificationNotes: [
      {
        id: "nt-4",
        author: "Admin (Pooja)",
        time: "26 Sep 2026, 02:45 PM",
        text: "Clarifying costume fittings and shoot schedule with lead choreographer before publishing.",
      },
    ],
    statusReason: "Need clarification on Jaipur shoot schedule travel arrangements and exact Kathak audition piece required.",
  },
  {
    id: "req-104",
    projectTitle: "Urban Youth Apparel Digital Campaign",
    recruiterId: "rec-202",
    recruiterName: "Priya Sundaram",
    company: "Ogilvy Creative Labs",
    projectType: "Digital Ad / Fashion",
    budget: "₹40,000 / day",
    budgetType: "Paid",
    submittedDate: "2026-09-30",
    status: "New",
    description: "Autumn streetwear youth lookbook digital ad campaign. Looking for modern street style models with energetic poses.",
    locations: "Bandra & South Mumbai Streets",
    shootStartDate: "2026-10-18",
    shootEndDate: "2026-10-19",
    deadline: "2026-10-10",
    requiredMaterials: ["Commercial Headshot", "Full Body Look"],
    roles: [
      {
        id: "r-5",
        roleName: "Streetwear Male & Female Leads",
        artistsCount: 4,
        ageRange: "19 - 25 years",
        gender: "Any",
        look: "Edgy, trendy streetwear, cool aesthetic",
        language: "English / Hindi",
        skills: "High fashion posing, skateboard/rollerblade basics a plus",
        notes: "Outdoor candid daylight shots.",
      },
    ],
    clarificationNotes: [],
    statusReason: null,
  },
  {
    id: "req-105",
    projectTitle: "Telugu Action Thriller 'Rakshak'",
    recruiterId: "rec-204",
    recruiterName: "Senthil Kumar",
    company: "Sun NXT Originals",
    projectType: "OTT Series",
    budget: "₹25,000 / day",
    budgetType: "Paid",
    submittedDate: "2026-09-15",
    status: "Declined",
    description: "Cop action web series shooting in Hyderabad outskirts.",
    locations: "Hyderabad Studios",
    shootStartDate: "2026-10-05",
    shootEndDate: "2026-10-25",
    deadline: "2026-09-25",
    requiredMaterials: ["Full Body Look", "Action Reel"],
    roles: [
      {
        id: "r-6",
        roleName: "Police Inspector Cadet",
        artistsCount: 2,
        ageRange: "25 - 32 years",
        gender: "Male",
        look: "Tall, athletic, strict demeanor",
        language: "Telugu (Fluent)",
        skills: "Stunt choreography",
        notes: "Heavy action sequences.",
      },
    ],
    clarificationNotes: [
      {
        id: "nt-5",
        author: "Admin (Sanjay)",
        time: "16 Sep 2026, 10:00 AM",
        text: "Contacted recruiter: Shoot dates too short (starts in 3 days) and insurance coverage for stunts not provided.",
      },
    ],
    statusReason: "Unrealistic lead time (3 days before shoot) and missing stunt safety insurance clearance.",
  },
];

export const initialCastingCalls = [
  {
    id: "cc-301",
    title: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    projectTitle: "Mumbai Diaries Season 2",
    category: "OTT Series",
    city: "Mumbai",
    locations: "Mumbai & Pune Studios",
    budgetLabel: "₹45k - ₹80k / day",
    budgetType: "Paid",
    budgetAmount: "₹60,000 / day average",
    deadline: "2026-10-15",
    applicationsCount: 64,
    status: "Live",
    description: "Critically acclaimed medical drama series returning for Season 2. Seeking talented lead and supporting artists for high-intensity hospital and investigative storylines.",
    shootLocation: "Mumbai & Pune Film City Studios",
    shootDates: "10 Nov 2026 - 20 Jan 2027",
    requiredMaterials: [
      "Commercial Headshot",
      "Full Body Look",
      "Dramatic Video Showreel",
      "Audition Monologue Self-Tape",
    ],
    eligibility: "Age 21-30, based in or able to travel to Mumbai. Verified Vismaya profiles only.",
    roles: [
      {
        id: "r-1",
        roleName: "Dr. Tanya Roy (Trauma Specialist)",
        artistsCount: 1,
        ageRange: "21 - 27 years",
        gender: "Female",
        look: "Sharp, intelligent, urban contemporary look",
        language: "Hindi (Fluent), English (Fluent)",
        skills: "Fast dialogue delivery, emotional control",
        notes: "Key role across 6 episodes.",
      },
      {
        id: "r-2",
        roleName: "Rohan Varma (Investigative Reporter)",
        artistsCount: 1,
        ageRange: "24 - 30 years",
        gender: "Male",
        look: "Intense, expressive eyes, rugged style",
        language: "Hindi, English",
        skills: "Voice modulation, high-stress scenes",
        notes: "Requires monologue test.",
      },
    ],
  },
  {
    id: "cc-302",
    title: "National Beverage Commercial TVC",
    projectTitle: "Summer Refresh TVC",
    category: "Commercial / TVC",
    city: "Mumbai",
    locations: "Film City Mumbai",
    budgetLabel: "₹1,20,000 lump sum",
    budgetType: "Paid",
    budgetAmount: "₹1,20,000 total",
    deadline: "2026-10-08",
    applicationsCount: 42,
    status: "Live",
    description: "Energetic and joyful beverage TV commercial campaign for national broadcast and digital OTT platforms.",
    shootLocation: "Mumbai Studio 4",
    shootDates: "18 Oct 2026 - 20 Oct 2026",
    requiredMaterials: ["Commercial Headshot", "Full Body Look", "Self-Tape Intro"],
    eligibility: "Open to male & female actors aged 18-26 with high energy expressions.",
    roles: [
      {
        id: "r-7",
        roleName: "Group of Friends (Leads)",
        artistsCount: 4,
        ageRange: "18 - 25 years",
        gender: "Any",
        look: "Vibrant, charming smiles, expressive eyes",
        language: "Hindi",
        skills: "Natural laughter, spontaneous reactions",
        notes: "Water splash & outdoor energy scenes.",
      },
    ],
  },
  {
    id: "cc-303",
    title: "Indie Feature Film 'Midnight in Fort'",
    projectTitle: "Midnight in Fort",
    category: "Feature Film",
    city: "Mumbai",
    locations: "South Mumbai Heritage Precincts",
    budgetLabel: "Travel + Stay Provided",
    budgetType: "Travel + Stay",
    budgetAmount: "₹15,000 / day + stay",
    deadline: "2026-10-25",
    applicationsCount: 29,
    status: "Live",
    description: "Atmospheric neo-noir indie feature film set in vintage Bombay streets. Directed by award-winning independent filmmaker.",
    shootLocation: "South Mumbai & Colaba",
    shootDates: "05 Nov 2026 - 25 Nov 2026",
    requiredMaterials: ["Dramatic Video Showreel", "Profile Photos", "Monologue"],
    eligibility: "Actors aged 24-40 with strong theater or indie film background.",
    roles: [
      {
        id: "r-8",
        roleName: "Detective Samar (Lead)",
        artistsCount: 1,
        ageRange: "28 - 38 years",
        gender: "Male",
        look: "Rugged, brooding, expressive gaze",
        language: "Hindi & English",
        skills: "Subtle nuanced acting, voice control",
        notes: "Night shoot schedule.",
      },
    ],
  },
  {
    id: "cc-304",
    title: "Premium Luxury Automobile Brand Film",
    projectTitle: "Apex Motors 2027 Launch",
    category: "Commercial / TVC",
    city: "Bangalore",
    locations: "Bangalore Tech Park & Airport Road",
    budgetLabel: "₹2,50,000 lump sum",
    budgetType: "Paid",
    budgetAmount: "₹2,50,000 total",
    deadline: "2026-11-01",
    applicationsCount: 0,
    status: "Draft",
    description: "Sophisticated corporate and lifestyle brand film for an electric luxury sedan launch.",
    shootLocation: "Bangalore Urban Locations",
    shootDates: "15 Nov 2026 - 17 Nov 2026",
    requiredMaterials: ["Commercial Headshot", "Suit / Formal Attire Look"],
    eligibility: "Professional models & actors aged 28-42 with charismatic executive presence.",
    roles: [
      {
        id: "r-9",
        roleName: "Visionary CEO & Driver",
        artistsCount: 2,
        ageRange: "28 - 40 years",
        gender: "Any",
        look: "Sophisticated, sharp facial features, confident posture",
        language: "English (Neutral accent)",
        skills: "Driving license mandatory, polished walking stride",
        notes: "Precision driving stunt double on set.",
      },
    ],
  },
  {
    id: "cc-305",
    title: "Monsoon Romance Music Video",
    projectTitle: "Baarish Mein Tum",
    category: "Music Video",
    city: "Goa",
    locations: "North Goa Beaches & Old Portuguese Villas",
    budgetLabel: "₹35,000 / day",
    budgetType: "Paid",
    budgetAmount: "₹35,000 / day",
    deadline: "2026-09-10",
    applicationsCount: 51,
    status: "Closed",
    description: "Romantic Hindi music video by T-Series. Filmed across scenic beaches and heritage mansions.",
    shootLocation: "Goa",
    shootDates: "15 Sep 2026 - 20 Sep 2026",
    requiredMaterials: ["Headshot", "Dance / Romantic Expression Reel"],
    eligibility: "Lead couple roles.",
    roles: [
      {
        id: "r-10",
        roleName: "Lead Couple (Aryan & Meera)",
        artistsCount: 2,
        ageRange: "20 - 26 years",
        gender: "Male & Female",
        look: "Photogenic, cinematic chemistry",
        language: "Hindi",
        skills: "Lip-syncing, subtle emotional expressions",
        notes: "Rain sequence scenes.",
      },
    ],
  },
];

export const initialAdminNotifications = [
  {
    id: "notif-adm-1",
    title: "New Talent Verification Request",
    message: "Aarav Mehra (Actor, 24, Mumbai) submitted profile verification.",
    time: "10 minutes ago",
    read: false,
    type: "talent",
    link: "/admin/talent-management",
  },
  {
    id: "notif-adm-2",
    title: "Minor Artist Consent Verification",
    message: "Ananya Deshmukh (Child Artist, 15) submitted guardian consent NOC.",
    time: "45 minutes ago",
    read: false,
    type: "talent",
    link: "/admin/talent-management",
  },
  {
    id: "notif-adm-3",
    title: "New Recruiter Registration",
    message: "Ogilvy Creative Labs submitted corporate CIN and GST verification.",
    time: "2 hours ago",
    read: false,
    type: "recruiter",
    link: "/admin/recruiter-management",
  },
  {
    id: "notif-adm-4",
    title: "New Requirement Request",
    message: "Urban Youth Apparel Campaign submitted by Ogilvy Creative Labs.",
    time: "3 hours ago",
    read: false,
    type: "requirement",
    link: "/admin/requirement-requests",
  },
  {
    id: "notif-adm-5",
    title: "Media Uploads Awaiting Review",
    message: "4 new photos and audition reels submitted to moderation queue.",
    time: "5 hours ago",
    read: true,
    type: "media",
    link: "/admin/media-moderation",
  },
  {
    id: "notif-adm-6",
    title: "Casting Call Applications Update",
    message: "Mumbai Diaries Season 2 received 64 talent submissions.",
    time: "1 day ago",
    read: true,
    type: "casting",
    link: "/admin/casting-calls",
  },
];

export const initialRecentAdminActivity = [
  {
    id: "act-1",
    title: "Requirement Clarification Logged",
    description: "Admin Sanjay logged phone clarification for 'Glow Skincare TVC' (₹1,50,000 lump sum confirmed).",
    time: "25 minutes ago",
    type: "requirement",
  },
  {
    id: "act-2",
    title: "Media File Approved",
    description: "Approved 'Profile Lookbook - Editorial 2026' for artist Riya Sharma.",
    time: "1 hour ago",
    type: "media",
  },
  {
    id: "act-3",
    title: "Recruiter Account Verified",
    description: "Verified Zee Films (CIN: U92100MH1992PLC068301) following compliance check.",
    time: "3 hours ago",
    type: "recruiter",
  },
  {
    id: "act-4",
    title: "Casting Call Published",
    description: "Published 'Mumbai Diaries Season 2' public casting call (2 roles).",
    time: "Yesterday",
    type: "casting",
  },
  {
    id: "act-5",
    title: "Talent Profile Verified",
    description: "Verified and approved artist profile for Riya Sharma (Mumbai).",
    time: "2 days ago",
    type: "talent",
  },
];

export const initialApplications = [
  {
    id: "app-101",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-904",
    applicantName: "Riya Sharma",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    age: 22,
    gender: "Female",
    city: "Mumbai",
    state: "Maharashtra",
    roleApplied: "Dr. Tanya Roy (Trauma Specialist)",
    appliedDate: "2026-09-29",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Trauma Room Monologue Self-Tape",
    status: "Shortlisted",
    email: "riya.sharma@vismaya.io",
    phone: "+91 98765 43210",
    experienceYears: "3 years",
    bio: "Barry John Acting Studio alumni with 3+ years in Marathi/Hindi short films & brand campaigns. Trained in classical Kathak with emotional intensity.",
    skills: ["Method Acting", "Kathak Dance", "Dialogue Delivery", "Medical Terms Flow"],
    languages: ["Hindi (Native)", "English (Fluent)", "Marathi (Fluent)"],
    physical: { height: "5'6\" (168 cm)", weight: "54 kg", skinTone: "Wheatish" },
    portfolio: [
      { id: "pf-1", title: "Commercial Headshot", type: "Photo", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80" },
      { id: "pf-2", title: "Kathak Monologue Reel", type: "Video", url: "https://www.w3schools.com/html/mov_bbb.mp4" }
    ],
    notes: "Top candidate for Dr. Tanya Roy. Strong medical scene audition tape.",
  },
  {
    id: "app-102",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-901",
    applicantName: "Aarav Mehra",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    age: 24,
    gender: "Male",
    city: "Mumbai",
    state: "Maharashtra",
    roleApplied: "Rohan Varma (Investigative Reporter)",
    appliedDate: "2026-09-30",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Investigative Exposé Self-Tape",
    status: "Shortlisted",
    email: "aarav.mehra@gmail.com",
    phone: "+91 98192 34567",
    experienceYears: "2.5 years",
    bio: "FTII trained screen actor with theater roots in Prithvi Theatre. Seeking gritty OTT roles.",
    skills: ["Screen Acting", "Method Acting", "Voice Over", "Bike Stunts"],
    languages: ["Hindi (Native)", "English (Fluent)", "Punjabi"],
    physical: { height: "5'11\" (180 cm)", weight: "72 kg", skinTone: "Wheatish" },
    portfolio: [
      { id: "pf-3", title: "Primary Headshot", type: "Photo", url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80" },
      { id: "pf-4", title: "Dramatic Showreel", type: "Video", url: "https://www.w3schools.com/html/mov_bbb.mp4" }
    ],
    notes: "Expressive eye acting. Fits investigative reporter tone.",
  },
  {
    id: "app-103",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-911",
    applicantName: "Pooja Hegde-Patil",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80",
    age: 25,
    gender: "Female",
    city: "Pune",
    state: "Maharashtra",
    roleApplied: "Dr. Tanya Roy (Trauma Specialist)",
    appliedDate: "2026-09-30",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Dr. Tanya Hospital Scene Audition",
    status: "Under Review",
    email: "pooja.patil@gmail.com",
    phone: "+91 98220 11998",
    experienceYears: "4 years",
    bio: "Marathi theater actor with 10+ live stage plays and 2 indie short films.",
    skills: ["Stage Drama", "Voice Modulation", "Marathi Diction"],
    languages: ["Marathi (Native)", "Hindi (Fluent)", "English (Fluent)"],
    physical: { height: "5'5\" (165 cm)", weight: "52 kg", skinTone: "Fair" },
    portfolio: [
      { id: "pf-5", title: "Studio Lookbook", type: "Photo", url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80" }
    ],
    notes: "Clean diction and steady performance.",
  },
  {
    id: "app-104",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-912",
    applicantName: "Siddharth Rao",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    age: 27,
    gender: "Male",
    city: "Mumbai",
    state: "Maharashtra",
    roleApplied: "Rohan Varma (Investigative Reporter)",
    appliedDate: "2026-10-01",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Crime Beat Monologue",
    status: "Under Review",
    email: "siddharth.rao@yahoo.com",
    phone: "+91 98204 77665",
    experienceYears: "5 years",
    bio: "Ex-journalist turned professional theater actor. 5 years in Mumbai theater circuit.",
    skills: ["Improv", "Live Monologues", "Voice Modulation"],
    languages: ["Hindi (Native)", "English (Fluent)", "Kannada"],
    physical: { height: "5'10\" (178 cm)", weight: "74 kg", skinTone: "Wheatish" },
    portfolio: [
      { id: "pf-6", title: "Headshot", type: "Photo", url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80" }
    ],
    notes: "Has actual journalism background; very natural pacing.",
  },
  {
    id: "app-105",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-905",
    applicantName: "Kabir Roy",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    age: 28,
    gender: "Male",
    city: "Kolkata",
    state: "West Bengal",
    roleApplied: "Rohan Varma (Investigative Reporter)",
    appliedDate: "2026-09-28",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Investigative Scene Self-Tape",
    status: "Shortlisted",
    email: "kabir.roy@gmail.com",
    phone: "+91 98300 87654",
    experienceYears: "5 years",
    bio: "Bengali theater artist with 5+ years experience transitioning into Pan-India OTT series.",
    skills: ["Intense Drama", "Physical Theater", "Swimming"],
    languages: ["Bengali (Native)", "Hindi (Fluent)", "English (Fluent)"],
    physical: { height: "6'0\" (183 cm)", weight: "78 kg", skinTone: "Fair" },
    portfolio: [
      { id: "pf-7", title: "Character Look", type: "Photo", url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80" }
    ],
    notes: "Powerful screen presence.",
  },
  {
    id: "app-106",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-915",
    applicantName: "Neha Verma",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80",
    age: 23,
    gender: "Female",
    city: "Delhi",
    state: "Delhi NCR",
    roleApplied: "Dr. Tanya Roy (Trauma Specialist)",
    appliedDate: "2026-10-01",
    hasAuditionClip: false,
    auditionClipUrl: null,
    auditionClipTitle: null,
    status: "Applied",
    email: "neha.verma@gmail.com",
    phone: "+91 98110 33445",
    experienceYears: "1 year",
    bio: "Delhi University theater society president. Trained in voice acting.",
    skills: ["Screen Acting", "Classical Music", "Improvisation"],
    languages: ["Hindi (Native)", "English (Fluent)"],
    physical: { height: "5'4\" (163 cm)", weight: "50 kg", skinTone: "Fair" },
    portfolio: [
      { id: "pf-8", title: "Portrait Headshot", type: "Photo", url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=80" }
    ],
    notes: "Audition tape missing.",
  },
  {
    id: "app-107",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-916",
    applicantName: "Arjun Kapoor-Sen",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    age: 29,
    gender: "Male",
    city: "Mumbai",
    state: "Maharashtra",
    roleApplied: "Rohan Varma (Investigative Reporter)",
    appliedDate: "2026-09-30",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Police Station Confrontation Reel",
    status: "Under Review",
    email: "arjun.ksen@gmail.com",
    phone: "+91 98200 44556",
    experienceYears: "6 years",
    bio: "Commercial model & OTT actor with 3 supporting roles on SonyLIV & Hotstar.",
    skills: ["Method Acting", "Martial Arts", "Dubbing"],
    languages: ["Hindi (Native)", "English (Fluent)", "Bengali"],
    physical: { height: "6'1\" (185 cm)", weight: "80 kg", skinTone: "Wheatish" },
    portfolio: [
      { id: "pf-9", title: "Editorial Look", type: "Photo", url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=80" }
    ],
    notes: "Experienced character actor.",
  },
  {
    id: "app-108",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-918",
    applicantName: "Isha Talwar-Nambiar",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80",
    age: 26,
    gender: "Female",
    city: "Mumbai",
    state: "Maharashtra",
    roleApplied: "Dr. Tanya Roy (Trauma Specialist)",
    appliedDate: "2026-09-29",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "ICU Triage Monologue",
    status: "Shortlisted",
    email: "isha.talwar@gmail.com",
    phone: "+91 98202 88776",
    experienceYears: "4 years",
    bio: "Trained in London Academy of Music and Dramatic Art (LAMDA). Experienced in medical thrillers.",
    skills: ["Dramatic Delivery", "Dialect Coaching", "Stage Combat"],
    languages: ["English (Native)", "Hindi (Fluent)", "Malayalam"],
    physical: { height: "5'7\" (170 cm)", weight: "56 kg", skinTone: "Fair" },
    portfolio: [
      { id: "pf-10", title: "Studio Comp Card", type: "Photo", url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80" }
    ],
    notes: "High caliber screen test.",
  },
  {
    id: "app-109",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-919",
    applicantName: "Kritika Kamra-Joshi",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    age: 24,
    gender: "Female",
    city: "Bangalore",
    state: "Karnataka",
    roleApplied: "Dr. Tanya Roy (Trauma Specialist)",
    appliedDate: "2026-09-28",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Tanya Audition Tape 2026",
    status: "Not Selected",
    email: "kritika.kj@gmail.com",
    phone: "+91 99800 12345",
    experienceYears: "2 years",
    bio: "Bangalore theater performer. Relocating to Mumbai.",
    skills: ["Classical Dance", "Screen Acting"],
    languages: ["English (Fluent)", "Kannada (Native)", "Hindi (Conversational)"],
    physical: { height: "5'5\" (165 cm)", weight: "53 kg", skinTone: "Wheatish" },
    portfolio: [],
    notes: "Hindi diction needs improvement for fast-paced medical terminology.",
  },
  {
    id: "app-110",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-920",
    applicantName: "Dev Joshi",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80",
    age: 25,
    gender: "Male",
    city: "Ahmedabad",
    state: "Gujarat",
    roleApplied: "Rohan Varma (Investigative Reporter)",
    appliedDate: "2026-10-01",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Newsroom Debate Audition",
    status: "Applied",
    email: "dev.joshi@gmail.com",
    phone: "+91 98790 55443",
    experienceYears: "3 years",
    bio: "Gujarati regional web series lead actor.",
    skills: ["Dialogue Delivery", "Voice Acting"],
    languages: ["Gujarati (Native)", "Hindi (Fluent)", "English (Conversational)"],
    physical: { height: "5'9\" (175 cm)", weight: "70 kg", skinTone: "Fair" },
    portfolio: [],
    notes: "Recent submission.",
  },
  {
    id: "app-111",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-921",
    applicantName: "Meera Sen",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80",
    age: 21,
    gender: "Female",
    city: "Mumbai",
    state: "Maharashtra",
    roleApplied: "Dr. Tanya Roy (Trauma Specialist)",
    appliedDate: "2026-09-29",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Trauma Ward Entry Scene",
    status: "Under Review",
    email: "meera.sen@outlook.com",
    phone: "+91 98200 99881",
    experienceYears: "2 years",
    bio: "Graduate from National School of Drama summer intensive.",
    skills: ["Physical Acting", "Contemporary Dance"],
    languages: ["Hindi (Native)", "English (Fluent)"],
    physical: { height: "5'6\" (168 cm)", weight: "52 kg", skinTone: "Dusky" },
    portfolio: [],
    notes: "Good emotional vulnerability.",
  },
  {
    id: "app-112",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-922",
    applicantName: "Sahil Anand",
    avatar: "https://images.unsplash.com/photo-1480429370139-e0132c086e2a?w=300&auto=format&fit=crop&q=80",
    age: 30,
    gender: "Male",
    city: "Delhi",
    state: "Delhi NCR",
    roleApplied: "Rohan Varma (Investigative Reporter)",
    appliedDate: "2026-09-27",
    hasAuditionClip: false,
    auditionClipUrl: null,
    auditionClipTitle: null,
    status: "Not Selected",
    email: "sahil.anand@gmail.com",
    phone: "+91 98111 99887",
    experienceYears: "7 years",
    bio: "Commercial voice over artist and TV episodic actor.",
    skills: ["Dubbing", "Hosting"],
    languages: ["Hindi (Native)", "English (Fluent)", "Punjabi"],
    physical: { height: "5'11\" (180 cm)", weight: "79 kg", skinTone: "Fair" },
    portfolio: [],
    notes: "Outside desired age range (over 28 limit for junior reporter).",
  },
  {
    id: "app-113",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-923",
    applicantName: "Tanvi Azmi-Roy",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80",
    age: 23,
    gender: "Female",
    city: "Mumbai",
    state: "Maharashtra",
    roleApplied: "Dr. Tanya Roy (Trauma Specialist)",
    appliedDate: "2026-09-30",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Doctor Patient Conflict Audition",
    status: "Applied",
    email: "tanvi.azmi@gmail.com",
    phone: "+91 98205 11223",
    experienceYears: "1.5 years",
    bio: "Whistling Woods International acting graduate.",
    skills: ["Screen Presence", "Horse Riding"],
    languages: ["Hindi (Native)", "English (Fluent)"],
    physical: { height: "5'7\" (170 cm)", weight: "55 kg", skinTone: "Fair" },
    portfolio: [],
    notes: "Promising fresh face.",
  },
  {
    id: "app-114",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-924",
    applicantName: "Rohan Mehra",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80",
    age: 26,
    gender: "Male",
    city: "Chandigarh",
    state: "Punjab",
    roleApplied: "Rohan Varma (Investigative Reporter)",
    appliedDate: "2026-09-29",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Undercover Sting Audition Tape",
    status: "Under Review",
    email: "rohan.mehra.chd@gmail.com",
    phone: "+91 98722 33445",
    experienceYears: "3 years",
    bio: "Punjab university theater actor.",
    skills: ["Method Acting", "Martial Arts"],
    languages: ["Punjabi (Native)", "Hindi (Fluent)", "English (Fluent)"],
    physical: { height: "6'0\" (183 cm)", weight: "76 kg", skinTone: "Fair" },
    portfolio: [],
    notes: "Energetic dialogue delivery.",
  },
  {
    id: "app-115",
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    talentId: "tal-925",
    applicantName: "Shreya Dhanwanthary-Rao",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80",
    age: 25,
    gender: "Female",
    city: "Hyderabad",
    state: "Telangana",
    roleApplied: "Dr. Tanya Roy (Trauma Specialist)",
    appliedDate: "2026-09-28",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Medical Emergency Monologue",
    status: "Under Review",
    email: "shreya.d@gmail.com",
    phone: "+91 94401 22334",
    experienceYears: "3.5 years",
    bio: "Multilingual OTT actress with experience in Telugu & Hindi web series.",
    skills: ["Screen Acting", "Fast Diction", "Voice Modulation"],
    languages: ["Telugu (Native)", "Hindi (Fluent)", "English (Fluent)"],
    physical: { height: "5'6\" (168 cm)", weight: "54 kg", skinTone: "Wheatish" },
    portfolio: [],
    notes: "Confident screen presence.",
  },
  // Additional applications for other calls
  {
    id: "app-201",
    callId: "cc-302",
    callTitle: "National Beverage Commercial TVC",
    talentId: "tal-904",
    applicantName: "Riya Sharma",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    age: 22,
    gender: "Female",
    city: "Mumbai",
    state: "Maharashtra",
    roleApplied: "Group of Friends (Leads)",
    appliedDate: "2026-10-01",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Beverage Sip & Joy Expression Self-Tape",
    status: "Shortlisted",
    email: "riya.sharma@vismaya.io",
    phone: "+91 98765 43210",
    experienceYears: "3 years",
    bio: "Kathak trained and high energy commercial face.",
    skills: ["Camera Ease", "Laughter", "Dance"],
    languages: ["Hindi (Native)", "English (Fluent)"],
    physical: { height: "5'6\" (168 cm)", weight: "54 kg", skinTone: "Wheatish" },
    portfolio: [],
    notes: "Great smile and vibrant expressions.",
  },
  {
    id: "app-301",
    callId: "cc-303",
    callTitle: "Indie Feature Film 'Midnight in Fort'",
    talentId: "tal-905",
    applicantName: "Kabir Roy",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    age: 28,
    gender: "Male",
    city: "Kolkata",
    state: "West Bengal",
    roleApplied: "Detective Samar (Lead)",
    appliedDate: "2026-09-29",
    hasAuditionClip: true,
    auditionClipUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    auditionClipTitle: "Noir Monologue Audition",
    status: "Under Review",
    email: "kabir.roy@gmail.com",
    phone: "+91 98300 87654",
    experienceYears: "5 years",
    bio: "Deep voice and brooding neo-noir screen presence.",
    skills: ["Method Acting", "Physical Theater"],
    languages: ["Bengali", "Hindi", "English"],
    physical: { height: "6'0\" (183 cm)", weight: "78 kg", skinTone: "Fair" },
    portfolio: [],
    notes: "Fits vintage 1970s detective aesthetic.",
  }
];

export const initialShortlists = {
  "cc-301": {
    callId: "cc-301",
    callTitle: "Mumbai Diaries Season 2 - Lead Doctor & Journalist Roles",
    recruiterId: "rec-201",
    recruiterCompany: "Zee Films",
    recruiterContact: "Vikram Malhotra",
    status: "Sent to recruiter",
    sentDate: "01 Oct 2026",
    recruiterFeedback: [
      {
        applicationId: "app-101",
        talentId: "tal-904",
        talentName: "Riya Sharma",
        roleName: "Dr. Tanya Roy (Trauma Specialist)",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
        city: "Mumbai",
        recruiterDecision: "Selected",
        starRating: 5,
        feedbackNotes: "Outstanding medical terminology flow and authentic hospital scene energy. Prime candidate for Tanya Roy.",
        auditionDateSuggestion: "2026-10-12, 11:30 AM",
        movedToBookings: false,
      },
      {
        applicationId: "app-102",
        talentId: "tal-901",
        talentName: "Aarav Mehra",
        roleName: "Rohan Varma (Investigative Reporter)",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
        city: "Mumbai",
        recruiterDecision: "Selected",
        starRating: 4,
        feedbackNotes: "Intense eye contact and solid voice modulation for high-stakes investigative scenes.",
        auditionDateSuggestion: "2026-10-12, 02:00 PM",
        movedToBookings: false,
      },
      {
        applicationId: "app-105",
        talentId: "tal-905",
        talentName: "Kabir Roy",
        roleName: "Rohan Varma (Investigative Reporter)",
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
        city: "Kolkata",
        recruiterDecision: "Rejected",
        starRating: 3,
        feedbackNotes: "Strong screen actor but accent did not fit the local Mumbai street reporter archetype.",
        auditionDateSuggestion: null,
        movedToBookings: false,
      },
      {
        applicationId: "app-108",
        talentId: "tal-918",
        talentName: "Isha Talwar-Nambiar",
        roleName: "Dr. Tanya Roy (Trauma Specialist)",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80",
        city: "Mumbai",
        recruiterDecision: "Selected",
        starRating: 5,
        feedbackNotes: "Exceptional dramatic range and screen poise. Great second callback option.",
        auditionDateSuggestion: "2026-10-13, 10:30 AM",
        movedToBookings: false,
      }
    ],
  },
  "cc-302": {
    callId: "cc-302",
    callTitle: "National Beverage Commercial TVC",
    recruiterId: "rec-202",
    recruiterCompany: "Ogilvy Creative Labs",
    recruiterContact: "Priya Sundaram",
    status: "Curating",
    sentDate: null,
    recruiterFeedback: [],
  }
};

export const initialBookings = [
  {
    id: "bk-701",
    talentId: "tal-904",
    talentName: "Riya Sharma",
    talentPhone: "+91 98765 43210",
    talentEmail: "riya.sharma@vismaya.io",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    projectTitle: "Mumbai Diaries Season 2",
    recruiterName: "Zee Films (Vikram Malhotra)",
    role: "Dr. Tanya Roy (Trauma Specialist)",
    auditionDate: "2026-10-12",
    auditionTime: "11:30 AM",
    location: "Studio 4, Famous Studios, Mahalaxmi, Mumbai",
    status: "Scheduled",
    lastUpdated: "2 hours ago",
    scriptSides: "Scene 14: Emergency Ward Resuscitation & Dialogue with Chief Surgeon. Look: Doctor Scrubs provided on set.",
    coordinationNotes: [
      {
        id: "cn-b1",
        author: "Admin Pooja",
        time: "01 Oct 2026, 03:00 PM",
        text: "Called Riya Sharma: Confirmed availability for 12 Oct 11:30 AM slot. Emailed script sides PDF."
      },
      {
        id: "cn-b2",
        author: "Admin Sanjay",
        time: "01 Oct 2026, 04:15 PM",
        text: "WhatsApp alert sent with location map and studio security entry pass details."
      }
    ]
  },
  {
    id: "bk-702",
    talentId: "tal-901",
    talentName: "Aarav Mehra",
    talentPhone: "+91 98192 34567",
    talentEmail: "aarav.mehra@gmail.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    projectTitle: "Mumbai Diaries Season 2",
    recruiterName: "Zee Films (Vikram Malhotra)",
    role: "Rohan Varma (Investigative Reporter)",
    auditionDate: "2026-10-12",
    auditionTime: "02:00 PM",
    location: "Studio 4, Famous Studios, Mahalaxmi, Mumbai",
    status: "Confirmed",
    lastUpdated: "1 day ago",
    scriptSides: "Scene 08: Confrontation with Hospital Director in Parking Lot.",
    coordinationNotes: [
      {
        id: "cn-b3",
        author: "Admin Sanjay",
        time: "30 Sep 2026, 05:30 PM",
        text: "Spoke to Aarav's talent manager. Time confirmed for 2:00 PM slot. Artist bringing own formal jacket look."
      }
    ]
  },
  {
    id: "bk-703",
    talentId: "tal-918",
    talentName: "Isha Talwar-Nambiar",
    talentPhone: "+91 98202 88776",
    talentEmail: "isha.talwar@gmail.com",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80",
    projectTitle: "Mumbai Diaries Season 2",
    recruiterName: "Zee Films (Vikram Malhotra)",
    role: "Dr. Tanya Roy (Trauma Specialist)",
    auditionDate: "2026-10-13",
    auditionTime: "10:30 AM",
    location: "Studio 4, Famous Studios, Mahalaxmi, Mumbai",
    status: "Selected",
    lastUpdated: "3 hours ago",
    scriptSides: "Scene 14: Emergency Ward Resuscitation & Diagnostic Monologue.",
    coordinationNotes: [
      {
        id: "cn-b4",
        author: "Admin Pooja",
        time: "01 Oct 2026, 01:15 PM",
        text: "Recruiter selected Isha as top callback option. Scheduled tentative slot for 13 Oct morning."
      }
    ]
  },
  {
    id: "bk-704",
    talentId: "tal-905",
    talentName: "Kabir Roy",
    talentPhone: "+91 98300 87654",
    talentEmail: "kabir.roy@gmail.com",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    projectTitle: "Hoichoi Thriller 'Chhaya'",
    recruiterName: "SVF Entertainment",
    role: "Antagonist (Bikram)",
    auditionDate: "2026-09-15",
    auditionTime: "03:30 PM",
    location: "Technicians Studio, Tollygunge, Kolkata",
    status: "Completed",
    lastUpdated: "2 weeks ago",
    scriptSides: "Courtroom interrogation climax scene.",
    coordinationNotes: [
      {
        id: "cn-b5",
        author: "Admin Sanjay",
        time: "15 Sep 2026, 06:00 PM",
        text: "Audition test successfully wrapped. Recruiter signed contract offline."
      }
    ]
  }
];

export const initialPayments = [
  {
    id: "pay-801",
    projectTitle: "Mumbai Diaries Season 2",
    payer: "Recruiter",
    payerName: "Zee Films (Vikram Malhotra)",
    grossAmount: 120000,
    commissionModel: "Charged to Recruiter (15%)",
    commissionPercent: 15,
    commissionAmount: 18000,
    talentPayout: 102000,
    paymentDate: "2026-09-28",
    paymentMode: "Bank Transfer",
    referenceNote: "UTR: HDFC882910392, Advance Retainer for Lead Medical Roles",
    status: "Received",
    talentName: "Riya Sharma",
    notes: "Offline NEFT confirmed with HDFC Corporate account.",
  },
  {
    id: "pay-802",
    projectTitle: "Glow Skincare National TVC",
    payer: "Recruiter",
    payerName: "Zee Films",
    grossAmount: 150000,
    commissionModel: "Charged to Recruiter (15%)",
    commissionPercent: 15,
    commissionAmount: 22500,
    talentPayout: 127500,
    paymentDate: "2026-09-25",
    paymentMode: "Bank Transfer",
    referenceNote: "UTR: ICIC000918231, Production Advance TVC",
    status: "Payout Pending",
    talentName: "Riya Sharma",
    notes: "Shoot scheduled for 24 Oct. Payout will be disbursed post shoot wrap.",
  },
  {
    id: "pay-803",
    projectTitle: "Summer Refresh TVC",
    payer: "Recruiter",
    payerName: "Ogilvy Creative Labs",
    grossAmount: 80000,
    commissionModel: "Charged to Recruiter (15%)",
    commissionPercent: 15,
    commissionAmount: 12000,
    talentPayout: 68000,
    paymentDate: "2026-09-20",
    paymentMode: "UPI",
    referenceNote: "UPI-Ref: 329102938102@kotak, Talent Casting Retainer",
    status: "Paid Out",
    talentName: "Aarav Mehra",
    notes: "Talent bank NEFT successfully transferred and verified offline.",
  },
  {
    id: "pay-804",
    projectTitle: "Tanishq Festive Digital Campaign",
    payer: "Talent",
    payerName: "Riya Sharma",
    grossAmount: 75000,
    commissionModel: "Charged to Talent (10%)",
    commissionPercent: 10,
    commissionAmount: 7500,
    talentPayout: 67500,
    paymentDate: "2026-09-10",
    paymentMode: "Bank Transfer",
    referenceNote: "NEFT: AXIS992810291, Campaign completion fee",
    status: "Paid Out",
    talentName: "Riya Sharma",
    notes: "Direct client settlement to talent, commission logged.",
  },
  {
    id: "pay-805",
    projectTitle: "Hoichoi Thriller 'Chhaya'",
    payer: "Recruiter",
    payerName: "SVF Entertainment",
    grossAmount: 60000,
    commissionModel: "Charged to Recruiter (15%)",
    commissionPercent: 15,
    commissionAmount: 9000,
    talentPayout: 51000,
    paymentDate: "2026-09-05",
    paymentMode: "Cheque",
    referenceNote: "Cheque #401928 drawn on SBI Kolkata Branch",
    status: "Paid Out",
    talentName: "Kabir Roy",
    notes: "Cheque cleared on 08 Sep.",
  }
];

export const initialSubscriptions = [
  {
    id: "sub-1",
    name: "Zee Films",
    userType: "Recruiter",
    plan: "Enterprise Studio Annual",
    amount: "₹60,000 / yr",
    status: "Paid",
    expiryDate: "2027-08-15",
    lastPaymentDate: "2026-08-15",
  },
  {
    id: "sub-2",
    name: "Ogilvy Creative Labs",
    userType: "Recruiter",
    plan: "Agency Enterprise Pro",
    amount: "₹45,000 / yr",
    status: "Paid",
    expiryDate: "2027-09-27",
    lastPaymentDate: "2026-09-27",
  },
  {
    id: "sub-3",
    name: "Mukesh Casting Studio",
    userType: "Recruiter",
    plan: "Boutique Casting Monthly",
    amount: "₹5,000 / mo",
    status: "Due",
    expiryDate: "2026-10-05",
    lastPaymentDate: "2026-09-05",
  },
  {
    id: "sub-4",
    name: "Sun NXT Originals",
    userType: "Recruiter",
    plan: "OTT Corporate Tier",
    amount: "₹75,000 / yr",
    status: "Paid",
    expiryDate: "2027-08-01",
    lastPaymentDate: "2026-08-01",
  },
  {
    id: "sub-5",
    name: "Riya Sharma",
    userType: "Talent",
    plan: "Spotlight Pro Artist",
    amount: "₹2,400 / yr",
    status: "Paid",
    expiryDate: "2027-08-15",
    lastPaymentDate: "2026-08-15",
  },
  {
    id: "sub-6",
    name: "Aarav Mehra",
    userType: "Talent",
    plan: "Spotlight Pro Artist",
    amount: "₹2,400 / yr",
    status: "Due",
    expiryDate: "2026-10-10",
    lastPaymentDate: "2025-10-10",
  },
  {
    id: "sub-7",
    name: "Vikram Chauhan",
    userType: "Talent",
    plan: "Basic Verified",
    amount: "₹1,200 / yr",
    status: "Expired",
    expiryDate: "2026-08-01",
    lastPaymentDate: "2025-08-01",
  }
];

export const initialAnalyticsData = {
  "30d": {
    kpis: {
      activeUsers: { value: "1,284", change: "+14.2%", isPositive: true },
      liveCalls: { value: "37", change: "+8.5%", isPositive: true },
      applications: { value: "2,910", change: "+22.1%", isPositive: true },
      revenue: { value: "₹4,85,000", change: "+18.4%", isPositive: true },
    },
    userGrowth: [
      { label: "Week 1", talent: 1120, recruiters: 84 },
      { label: "Week 2", talent: 1180, recruiters: 92 },
      { label: "Week 3", talent: 1235, recruiters: 104 },
      { label: "Week 4", talent: 1284, recruiters: 118 },
    ],
    applicationsMonthly: [
      { month: "May", count: 1420 },
      { month: "Jun", count: 1850 },
      { month: "Jul", count: 2100 },
      { month: "Aug", count: 2450 },
      { month: "Sep", count: 2780 },
      { month: "Oct", count: 2910 },
    ],
    categories: [
      { name: "OTT Series", value: 42, color: "var(--primary)" },
      { name: "Feature Film", value: 28, color: "var(--secondary)" },
      { name: "Commercial / TVC", value: 18, color: "var(--warning)" },
      { name: "Music Video", value: 8, color: "var(--success)" },
      { name: "Short Film & Others", value: 4, color: "var(--accent-green)" },
    ],
    funnel: [
      { stage: "Applied Submissions", count: 2910, percent: 100, color: "var(--primary)" },
      { stage: "Under Admin Review", count: 1688, percent: 58, color: "var(--dark-green)" },
      { stage: "Shortlisted for Recruiter", count: 407, percent: 14, color: "var(--secondary)" },
      { stage: "Auditioned & Booked", count: 122, percent: 4.2, color: "var(--success)" },
    ],
    revenueTrend: [
      { label: "May", revenue: 280000, commission: 42000 },
      { label: "Jun", revenue: 340000, commission: 51000 },
      { label: "Jul", revenue: 390000, commission: 58500 },
      { label: "Aug", revenue: 430000, commission: 64500 },
      { label: "Sep", revenue: 460000, commission: 69000 },
      { label: "Oct", revenue: 485000, commission: 72750 },
    ],
    topCities: [
      { city: "Mumbai", share: 54, count: "693 artists" },
      { city: "Delhi NCR", share: 21, count: "270 artists" },
      { city: "Bangalore", share: 12, count: "154 artists" },
      { city: "Hyderabad", share: 8, count: "102 artists" },
      { city: "Kolkata & Others", share: 5, count: "65 artists" },
    ]
  },
  "7d": {
    kpis: {
      activeUsers: { value: "1,284", change: "+3.8%", isPositive: true },
      liveCalls: { value: "37", change: "+2 calls", isPositive: true },
      applications: { value: "482", change: "+12.0%", isPositive: true },
      revenue: { value: "₹1,20,000", change: "+9.2%", isPositive: true },
    },
    userGrowth: [
      { label: "Mon", talent: 1260, recruiters: 114 },
      { label: "Tue", talent: 1268, recruiters: 115 },
      { label: "Wed", talent: 1272, recruiters: 116 },
      { label: "Thu", talent: 1278, recruiters: 117 },
      { label: "Fri", talent: 1284, recruiters: 118 },
    ],
    applicationsMonthly: [
      { month: "Mon", count: 68 },
      { month: "Tue", count: 94 },
      { month: "Wed", count: 110 },
      { month: "Thu", count: 104 },
      { month: "Fri", count: 106 },
    ],
    categories: [
      { name: "OTT Series", value: 45, color: "var(--primary)" },
      { name: "Feature Film", value: 25, color: "var(--secondary)" },
      { name: "Commercial / TVC", value: 20, color: "var(--warning)" },
      { name: "Music Video", value: 10, color: "var(--success)" },
    ],
    funnel: [
      { stage: "Applied Submissions", count: 482, percent: 100, color: "var(--primary)" },
      { stage: "Under Admin Review", count: 310, percent: 64, color: "var(--dark-green)" },
      { stage: "Shortlisted for Recruiter", count: 92, percent: 19, color: "var(--secondary)" },
      { stage: "Auditioned & Booked", count: 28, percent: 5.8, color: "var(--success)" },
    ],
    revenueTrend: [
      { label: "Mon", revenue: 20000, commission: 3000 },
      { label: "Tue", revenue: 25000, commission: 3750 },
      { label: "Wed", revenue: 35000, commission: 5250 },
      { label: "Thu", revenue: 20000, commission: 3000 },
      { label: "Fri", revenue: 20000, commission: 3000 },
    ],
    topCities: [
      { city: "Mumbai", share: 58, count: "280 artists" },
      { city: "Delhi NCR", share: 20, count: "96 artists" },
      { city: "Bangalore", share: 11, count: "53 artists" },
      { city: "Hyderabad", share: 7, count: "34 artists" },
      { city: "Others", share: 4, count: "19 artists" },
    ]
  },
  "90d": {
    kpis: {
      activeUsers: { value: "1,284", change: "+38.4%", isPositive: true },
      liveCalls: { value: "37", change: "+16 calls", isPositive: true },
      applications: { value: "7,840", change: "+44.2%", isPositive: true },
      revenue: { value: "₹14,20,000", change: "+32.1%", isPositive: true },
    },
    userGrowth: [
      { label: "Jul", talent: 940, recruiters: 68 },
      { label: "Aug", talent: 1080, recruiters: 88 },
      { label: "Sep", talent: 1284, recruiters: 118 },
    ],
    applicationsMonthly: [
      { month: "Jul", count: 2100 },
      { month: "Aug", count: 2450 },
      { month: "Sep", count: 2780 },
    ],
    categories: [
      { name: "OTT Series", value: 40, color: "var(--primary)" },
      { name: "Feature Film", value: 30, color: "var(--secondary)" },
      { name: "Commercial / TVC", value: 18, color: "var(--warning)" },
      { name: "Music Video", value: 12, color: "var(--success)" },
    ],
    funnel: [
      { stage: "Applied Submissions", count: 7840, percent: 100, color: "var(--primary)" },
      { stage: "Under Admin Review", count: 4800, percent: 61, color: "var(--dark-green)" },
      { stage: "Shortlisted for Recruiter", count: 1250, percent: 16, color: "var(--secondary)" },
      { stage: "Auditioned & Booked", count: 390, percent: 5.0, color: "var(--success)" },
    ],
    revenueTrend: [
      { label: "Jul", revenue: 390000, commission: 58500 },
      { label: "Aug", revenue: 430000, commission: 64500 },
      { label: "Sep", revenue: 600000, commission: 90000 },
    ],
    topCities: [
      { city: "Mumbai", share: 52, count: "668 artists" },
      { city: "Delhi NCR", share: 22, count: "282 artists" },
      { city: "Bangalore", share: 13, count: "167 artists" },
      { city: "Hyderabad", share: 8, count: "103 artists" },
      { city: "Kolkata & Others", share: 5, count: "64 artists" },
    ]
  },
  "1y": {
    kpis: {
      activeUsers: { value: "1,284", change: "+148%", isPositive: true },
      liveCalls: { value: "37", change: "+37 calls", isPositive: true },
      applications: { value: "18,400", change: "+210%", isPositive: true },
      revenue: { value: "₹48,50,000", change: "+185%", isPositive: true },
    },
    userGrowth: [
      { label: "Q1", talent: 450, recruiters: 32 },
      { label: "Q2", talent: 780, recruiters: 58 },
      { label: "Q3", talent: 1050, recruiters: 86 },
      { label: "Q4", talent: 1284, recruiters: 118 },
    ],
    applicationsMonthly: [
      { month: "Q1", count: 2800 },
      { month: "Q2", count: 4400 },
      { month: "Q3", count: 5800 },
      { month: "Q4", count: 5400 },
    ],
    categories: [
      { name: "OTT Series", value: 38, color: "var(--primary)" },
      { name: "Feature Film", value: 32, color: "var(--secondary)" },
      { name: "Commercial / TVC", value: 20, color: "var(--warning)" },
      { name: "Music Video", value: 10, color: "var(--success)" },
    ],
    funnel: [
      { stage: "Applied Submissions", count: 18400, percent: 100, color: "var(--primary)" },
      { stage: "Under Admin Review", count: 11200, percent: 61, color: "var(--dark-green)" },
      { stage: "Shortlisted for Recruiter", count: 2900, percent: 15.7, color: "var(--secondary)" },
      { stage: "Auditioned & Booked", count: 910, percent: 4.9, color: "var(--success)" },
    ],
    revenueTrend: [
      { label: "Q1", revenue: 850000, commission: 127500 },
      { label: "Q2", revenue: 1150000, commission: 172500 },
      { label: "Q3", revenue: 1380000, commission: 207000 },
      { label: "Q4", revenue: 1470000, commission: 220500 },
    ],
    topCities: [
      { city: "Mumbai", share: 50, count: "642 artists" },
      { city: "Delhi NCR", share: 22, count: "282 artists" },
      { city: "Bangalore", share: 14, count: "180 artists" },
      { city: "Hyderabad", share: 8, count: "103 artists" },
      { city: "Kolkata & Others", share: 6, count: "77 artists" },
    ]
  }
};

export const initialBroadcasts = [
  {
    id: "bc-1",
    title: "Mumbai Diaries Auditions Callback Notice",
    audience: "Verified Talent (Mumbai)",
    channel: "In-app + Urgent SMS",
    priority: "Urgent Casting Alert",
    sentAt: "Yesterday, 04:30 PM",
    recipientsCount: 340,
    message: "Callbacks for Mumbai Diaries Season 2 are underway. Check your notifications for slot details and script sides.",
  },
  {
    id: "bc-2",
    title: "New Commercial Requirements Portal Open",
    audience: "All Recruiters",
    channel: "In-app Notification",
    priority: "Normal",
    sentAt: "3 days ago",
    recipientsCount: 118,
    message: "Diwali festive TVC brief submissions are now open for expedited admin review.",
  }
];

