export const initialCompanyProfile = {
  companyName: "Zee Films",
  companyType: "Production House",
  registrationNumber: "CIN: U92100MH1992PLC068301",
  gstNumber: "27AAACZ1234F1Z8",
  website: "https://zeefilms.com",
  address: "Plot 19, Film City Complex, Goregaon East, Mumbai, Maharashtra 400065",
  contactPerson: "Vikram Malhotra",
  contactEmail: "vikram.malhotra@zeefilms.com",
  contactPhone: "+91 98201 54321",
  avatar: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=300&auto=format&fit=crop&q=80",
  verificationStatus: "Verified",
  verifiedAt: "15 August 2026",
  adminReason: "Corporate CIN and GST registration credentials verified by Vismaya Compliance Desk.",
};

export const initialRequirements = [
  {
    id: "req-101",
    title: "Mumbai Diaries Season 2",
    type: "OTT",
    description: "Critically acclaimed medical drama series returning for Season 2. Seeking talented lead and supporting artists for high-intensity hospital and investigative storylines.",
    locations: "Mumbai & Pune Studios",
    shootStartDate: "2026-11-10",
    shootEndDate: "2027-01-20",
    submittedDate: "2026-09-12",
    status: "Live",
    statusStage: 3, // 1: Submitted, 2: Under Admin Review, 3: Live, 4: Closed
    budgetType: "Paid",
    budgetRange: "₹45,000 - ₹80,000 / day",
    deadline: "2026-10-15",
    requiredMaterials: [
      "Commercial Headshot",
      "Full Body Look",
      "Dramatic Video Showreel",
      "Audition Monologue Self-Tape",
    ],
    roles: [
      {
        id: "r-1",
        roleName: "Dr. Tanya Roy (Trauma Specialist)",
        artistsCount: 1,
        ageRange: "21 - 27 years",
        gender: "Female",
        look: "Sharp, intelligent, urban contemporary look",
        language: "Hindi (Fluent), English (Fluent)",
        skills: "Fast dialogue delivery, emotional control",
        notes: "Key role across 6 episodes.",
      },
      {
        id: "r-2",
        roleName: "Rohan Varma (Investigative Reporter)",
        artistsCount: 1,
        ageRange: "24 - 30 years",
        gender: "Male",
        look: "Intense, expressive eyes, rugged style",
        language: "Hindi, English",
        skills: "Voice modulation, high-stress scenes",
        notes: "Requires monologue test.",
      },
    ],
    applicantsCount: 64,
    hasShortlist: true,
    shortlistCount: 4,
    shortlistFeedbackSent: false,
    adminNote: "Admin: 4 verified top-tier candidates curated for Dr. Tanya Roy and Rohan Varma roles.",
  },
  {
    id: "req-102",
    title: "Glow Skincare National TVC",
    type: "Ad",
    description: "Premium commercial TVC & digital campaign for a luxury botanical skincare range. Focusing on close-up skin radiance and natural expressions.",
    locations: "Mumbai (Famous Studios)",
    shootStartDate: "2026-10-24",
    shootEndDate: "2026-10-26",
    submittedDate: "2026-09-18",
    status: "Live",
    statusStage: 3,
    budgetType: "Paid",
    budgetRange: "₹1,50,000 lump sum",
    deadline: "2026-10-06",
    requiredMaterials: ["Commercial Headshot", "Full Body Look", "Audition Monologue Self-Tape"],
    roles: [
      {
        id: "r-3",
        roleName: "Lead Female Face (Natural Radiance)",
        artistsCount: 2,
        ageRange: "20 - 26 years",
        gender: "Female",
        look: "Photogenic smile, natural skin tone, expressive eyes",
        language: "Hindi",
        skills: "Camera ease, subtle facial reactions",
        notes: "Macro beauty lighting shots.",
      },
    ],
    applicantsCount: 38,
    hasShortlist: true,
    shortlistCount: 3,
    shortlistFeedbackSent: false,
    adminNote: "Admin needs a budget clarification on Glow Skincare TVC, we will call you.",
  },
  {
    id: "req-103",
    title: "Period Historical Feature Film 'Samrat'",
    type: "Film",
    description: "Grand historical theatrical feature film exploring royal classical arts of 16th-century India.",
    locations: "Jaipur Heritage Palaces & Film City",
    shootStartDate: "2026-12-01",
    shootEndDate: "2027-02-28",
    submittedDate: "2026-09-25",
    status: "Under Admin Review",
    statusStage: 2,
    budgetType: "Travel + Stay",
    budgetRange: "₹3,00,000 + Outstation Travel & Stay",
    deadline: "2026-10-20",
    requiredMaterials: ["Commercial Headshot", "Dramatic Video Showreel", "Audition Monologue Self-Tape"],
    roles: [
      {
        id: "r-4",
        roleName: "Priyamvada (Court Classical Dancer)",
        artistsCount: 1,
        ageRange: "20 - 26 years",
        gender: "Female",
        look: "Classical Indian features, graceful posture",
        language: "Hindi & Urdu diction",
        skills: "Classical dance (Kathak mandatory)",
        notes: "Choreography test side included.",
      },
    ],
    applicantsCount: 0,
    hasShortlist: false,
    shortlistCount: 0,
    shortlistFeedbackSent: false,
    adminNote: "Admin: Clarifying costume fittings and shoot schedule with lead choreographer before publishing.",
  },
];

export const initialShortlistedTalent = {
  "req-101": [
    {
      id: "cand-1",
      name: "Riya Sharma",
      age: 22,
      city: "Mumbai",
      height: "5'6\" (168 cm)",
      gender: "Female",
      primaryRole: "Dr. Tanya Roy",
      languages: ["Hindi (Native)", "English (Fluent)", "Marathi"],
      skills: ["Method Acting", "Kathak Dance", "Medical Terminology Flow"],
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
      gradient: "linear-gradient(135deg, #25502f 0%, #6fa876 100%)",
      initials: "RS",
      matchScore: "96%",
      adminScore: "9.4 / 10",
      auditionClipTitle: "Dr. Tanya Emergency Room Monologue",
      auditionDuration: "1:24 min",
      adminCuratorNote: "Trained at Barry John Studio. Outstanding command over high-stress dramatic dialogue.",
      experience: "Lead in student short film 'Awaaz' (Whistling Woods), Tanishq Campaign, Prithvi Theatre actor.",
      physicalAttributes: "Height: 5'6\" • Weight: 54kg • Skin Tone: Wheatish • Eyes: Hazel Brown",
      portfolioCount: 6,
      selectionStatus: "Pending", // "Selected" | "Rejected" | "Pending"
      starRating: 5,
    },
    {
      id: "cand-2",
      name: "Ananya Deshmukh",
      age: 24,
      city: "Mumbai",
      height: "5'7\" (170 cm)",
      gender: "Female",
      primaryRole: "Dr. Tanya Roy",
      languages: ["Hindi", "English", "Marathi"],
      skills: ["Screen Acting", "Emotional Control", "Dialogue Modulation"],
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80",
      gradient: "linear-gradient(135deg, #25502f 0%, #8fbf8a 100%)",
      initials: "AD",
      matchScore: "92%",
      adminScore: "8.9 / 10",
      auditionClipTitle: "Surgical ICU Monologue Self-Tape",
      auditionDuration: "1:10 min",
      adminCuratorNote: "Strong screen presence with understated, authentic facial reactions.",
      experience: "Supporting actor in Amazon mini-series, TV commercial for ICICI Bank.",
      physicalAttributes: "Height: 5'7\" • Weight: 56kg • Skin Tone: Fair • Eyes: Dark Brown",
      portfolioCount: 4,
      selectionStatus: "Pending",
      starRating: 4,
    },
    {
      id: "cand-3",
      name: "Kabir Mehra",
      age: 26,
      city: "Delhi NCR",
      height: "5'11\" (180 cm)",
      gender: "Male",
      primaryRole: "Rohan Varma",
      languages: ["Hindi (Native)", "English (Fluent)", "Punjabi"],
      skills: ["Fast-Paced Dialogue", "Intense Expression", "Stage Movement"],
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
      gradient: "linear-gradient(135deg, #1f7a4f 0%, #6fa876 100%)",
      initials: "KM",
      matchScore: "94%",
      adminScore: "9.1 / 10",
      auditionClipTitle: "Investigative Reporter Expose Monologue",
      auditionDuration: "1:45 min",
      adminCuratorNote: "National School of Drama graduate. Dynamic energy and sharp camera timing.",
      experience: "Lead in indie feature 'Raasta', multiple digital commercials.",
      physicalAttributes: "Height: 5'11\" • Weight: 74kg • Skin Tone: Wheatish • Eyes: Black",
      portfolioCount: 5,
      selectionStatus: "Pending",
      starRating: 5,
    },
    {
      id: "cand-4",
      name: "Siddharth Roy",
      age: 27,
      city: "Mumbai",
      height: "6'0\" (183 cm)",
      gender: "Male",
      primaryRole: "Rohan Varma",
      languages: ["Hindi", "English", "Bengali"],
      skills: ["Action Coordination", "Intense Facial Focus", "Voice Over"],
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
      gradient: "linear-gradient(135deg, #25502f 0%, #bfe3b4 100%)",
      initials: "SR",
      matchScore: "88%",
      adminScore: "8.6 / 10",
      auditionClipTitle: "Crime Beat Confrontation Scene",
      auditionDuration: "1:15 min",
      adminCuratorNote: "Sharp baritone voice, authoritative screen presence.",
      experience: "Featured in Hotstar crime thriller, multiple corporate brand films.",
      physicalAttributes: "Height: 6'0\" • Weight: 76kg • Skin Tone: Fair • Eyes: Dark Brown",
      portfolioCount: 4,
      selectionStatus: "Pending",
      starRating: 3,
    },
  ],
  "req-102": [
    {
      id: "cand-5",
      name: "Tara D'Souza",
      age: 21,
      city: "Mumbai",
      height: "5'7\" (170 cm)",
      gender: "Female",
      primaryRole: "Lead Female Face",
      languages: ["English", "Hindi"],
      skills: ["Beauty Modeling", "Subtle Smile", "High-Fashion Posing"],
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80",
      gradient: "linear-gradient(135deg, #4a6550 0%, #8fbf8a 100%)",
      initials: "TD",
      matchScore: "97%",
      adminScore: "9.6 / 10",
      auditionClipTitle: "Macro Beauty Skin Radiance Test",
      auditionDuration: "0:50 min",
      adminCuratorNote: "Flawless close-up camera presence, exceptional skin texture.",
      experience: "Vogue India digital lookbook, Lakme campaign.",
      physicalAttributes: "Height: 5'7\" • Weight: 52kg • Skin Tone: Olive • Eyes: Greenish Brown",
      portfolioCount: 8,
      selectionStatus: "Pending",
      starRating: 5,
    },
    {
      id: "cand-6",
      name: "Sanya Kapoor",
      age: 23,
      city: "Bengaluru",
      height: "5'5\" (165 cm)",
      gender: "Female",
      primaryRole: "Lead Female Face",
      languages: ["Hindi", "English", "Kannada"],
      skills: ["Camera Charisma", "Expressive Eyes", "Voice Modulation"],
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80",
      gradient: "linear-gradient(135deg, #1f7a4f 0%, #bfe3b4 100%)",
      initials: "SK",
      matchScore: "91%",
      adminScore: "9.0 / 10",
      auditionClipTitle: "Morning Glow Self-Tape",
      auditionDuration: "1:05 min",
      adminCuratorNote: "Warm, natural aura with effortless smiling delivery.",
      experience: "Nykaa commercial, Fastrack ad campaign.",
      physicalAttributes: "Height: 5'5\" • Weight: 50kg • Skin Tone: Fair • Eyes: Black",
      portfolioCount: 5,
      selectionStatus: "Pending",
      starRating: 4,
    },
    {
      id: "cand-7",
      name: "Pooja Hegde (Artist)",
      age: 22,
      city: "Mumbai",
      height: "5'6\" (168 cm)",
      gender: "Female",
      primaryRole: "Lead Female Face",
      languages: ["Hindi", "English"],
      skills: ["Minimal Makeup Look", "Subtle Smile"],
      avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80",
      gradient: "linear-gradient(135deg, #25502f 0%, #6fa876 100%)",
      initials: "PH",
      matchScore: "89%",
      adminScore: "8.7 / 10",
      auditionClipTitle: "Natural Light Monologue & Comp Card",
      auditionDuration: "1:00 min",
      adminCuratorNote: "Great natural symmetry for high-definition close-up shots.",
      experience: "L'Oreal digital feature, multiple boutique apparel shoots.",
      physicalAttributes: "Height: 5'6\" • Weight: 53kg • Skin Tone: Wheatish • Eyes: Hazel",
      portfolioCount: 4,
      selectionStatus: "Pending",
      starRating: 4,
    },
  ],
};

export const initialRecruiterNotifications = [
  {
    id: "n-1",
    title: "Shortlist ready: Mumbai Diaries S2",
    message: "Admin has curated and approved 4 top-tier actor profiles matching your casting requirements for Dr. Tanya Roy and Rohan Varma.",
    type: "Shortlists",
    time: "2 hours ago",
    read: false,
    actionHref: "/recruiter/shortlisted-talent?req=req-101",
    badge: "Shortlist Ready",
  },
  {
    id: "n-2",
    title: "Admin needs a budget clarification on Glow Skincare TVC",
    message: "Vismaya Casting Desk noted a question regarding usage rights and buyout fees. Our coordinator will contact you offline.",
    type: "Admin Messages",
    time: "5 hours ago",
    read: false,
    actionHref: "/recruiter/my-requirements",
    badge: "Admin Note",
  },
  {
    id: "n-3",
    title: "Your requirement is now live",
    message: "Glow Skincare National TVC casting brief is now live on the Vismaya Talent Portal accepting verified artist applications.",
    type: "Requirements",
    time: "1 day ago",
    read: false,
    actionHref: "/recruiter/my-requirements",
    badge: "Casting Call Live",
  },
  {
    id: "n-4",
    title: "Shortlist ready: Glow Skincare National TVC",
    message: "Admin shortlisted 3 verified beauty models with verified comp cards for your skincare TVC.",
    type: "Shortlists",
    time: "2 days ago",
    read: true,
    actionHref: "/recruiter/shortlisted-talent?req=req-102",
    badge: "Shortlist Ready",
  },
  {
    id: "n-5",
    title: "Company Verification Approved: Zee Films",
    message: "Your corporate production house account is officially verified. You can now post live casting requirements.",
    type: "Requirements",
    time: "3 days ago",
    read: true,
    actionHref: "/recruiter/settings",
    badge: "Verified",
  },
];

export const initialRecentActivity = [
  {
    id: "act-1",
    title: "Candidate Shortlist Received",
    description: "4 verified candidates curated by Admin for 'Mumbai Diaries Season 2'",
    time: "2 hours ago",
    type: "shortlist",
  },
  {
    id: "act-2",
    title: "Admin Note Added",
    description: "Clarification request on 'Glow Skincare National TVC' usage buyout",
    time: "5 hours ago",
    type: "admin",
  },
  {
    id: "act-3",
    title: "Requirement Approved & Live",
    description: "'Glow Skincare National TVC' was published to verified artists",
    time: "1 day ago",
    type: "live",
  },
  {
    id: "act-4",
    title: "Requirement Submitted",
    description: "'Period Historical Feature Film Samrat' sent for Admin moderation",
    time: "2 days ago",
    type: "submitted",
  },
];
