/**
 * Mock data for Vismaya Talent Dashboard
 * All dummy data is centralized here so components never hardcode data.
 */

export const initialProfileData = {
  id: "tal_904",
  status: "Approved", // Draft, Submitted, Approved, Rejected
  statusNote: "Your profile has been verified and approved by Vismaya Admin. You can now apply to live casting calls.",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
  
  // 1. Personal Details
  personal: {
    fullName: "Riya Sharma",
    stageName: "Riya Sharma",
    age: 22,
    dob: "2004-04-12",
    gender: "Female",
    city: "Mumbai",
    state: "Maharashtra",
    phone: "+91 98765 43210",
    email: "riya.sharma@vismaya.io",
    bio: "Passionate and theater-trained actress with 3+ years experience in Hindi & Marathi short films, web content, and commercials. Trained in classical Kathak with strong improvisation, emotional depth, and voice modulation.",
    primaryRole: "Actor / Model",
    instagram: "@riyasharma.act",
    imdb: "imdb.me/riyasharma",
  },

  // 2. Physical Attributes
  physical: {
    height: "5'6\" (168 cm)",
    weight: "54 kg",
    skinTone: "Wheatish",
    hairColor: "Dark Brown",
    hairLength: "Medium / Shoulder Length",
    eyeColor: "Hazel Brown",
    bodyType: "Slim / Athletic",
    chest: "34\"",
    waist: "26\"",
    hips: "36\"",
    shoeSize: "UK 6 / EU 39",
    tattoos: "None",
    piercings: "Ear lobes only",
  },

  // 3. Skills & Languages
  skills: [
    "Method Acting",
    "Kathak Dance",
    "Voice Over",
    "Horse Riding",
    "Stage Combat",
    "Improvisation",
    "Western Contemporary",
    "Swimming",
  ],
  languages: [
    "Hindi (Native)",
    "English (Fluent)",
    "Marathi (Fluent)",
    "Gujarati (Conversational)",
  ],

  // 4. Training & Experience
  experience: [
    {
      id: "exp-1",
      role: "Protagonist (Nisha)",
      project: "Short Film 'Awaaz' (Streaming on MUBI)",
      production: "Whistling Woods International",
      year: "2025",
      type: "Film",
      notes: "Lead character dealing with psychological drama. Won Best Student Short at Mumbai CineFest.",
    },
    {
      id: "exp-2",
      role: "Supporting Lead (Bride's Sister)",
      project: "Tanishq Festive Digital Campaign",
      production: "Famous Studios Mumbai",
      year: "2024",
      type: "Advertisement",
      notes: "High-visibility national digital & social media campaign across India.",
    },
    {
      id: "exp-3",
      role: "Theater Ensemble (Tara)",
      project: "Play: 'Andha Yug' Directed by K. Mehta",
      production: "Prithvi Theatre Mumbai",
      year: "2023",
      type: "Theater",
      notes: "Live monologue performance in over 12 stage shows across Mumbai & Pune.",
    },
  ],
  training: [
    {
      id: "trn-1",
      institute: "Barry John Acting Studio, Mumbai",
      course: "Diploma in Dramatic Arts & Screen Acting",
      year: "2023",
    },
    {
      id: "trn-2",
      institute: "Gandharva Mahavidyalaya",
      course: "Senior Diploma in Classical Kathak",
      year: "2021",
    },
  ],

  // 5. Availability & Location
  availability: {
    availableDays: ["Weekdays", "Weekends", "Full Time Shoot"],
    willingToTravel: true,
    hasPassport: true,
    preferredCities: ["Mumbai", "Delhi NCR", "Hyderabad", "Goa", "Pune", "Bangalore"],
    noticePeriod: "Immediate / 3 Days",
  },

  // 6. Guardian Consent (Conditional when age < 18)
  guardianConsent: {
    guardianName: "",
    relation: "",
    phone: "",
    email: "",
    govIdType: "Aadhaar Card",
    govIdNumber: "",
    idFileUploaded: false,
    consentGiven: false,
  },
};

export const initialPortfolioMedia = [
  {
    id: "m-1",
    title: "Commercial Studio Headshot - Natural Look",
    type: "Headshot",
    date: "2026-09-15",
    status: "Approved",
    url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    gradient: "linear-gradient(135deg, #25502f 0%, #6fa876 100%)",
    fileSize: "2.4 MB",
    resolution: "3000 x 4000 px",
  },
  {
    id: "m-2",
    title: "Full Body - Traditional Festive Saree Look",
    type: "Full Body",
    date: "2026-09-18",
    status: "Approved",
    url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80",
    gradient: "linear-gradient(135deg, #25502f 0%, #8fbf8a 100%)",
    fileSize: "3.8 MB",
    resolution: "2400 x 3600 px",
  },
  {
    id: "m-3",
    title: "Dramatic Monologue Showreel (2026 Edition)",
    type: "Showreel",
    date: "2026-09-22",
    status: "Approved",
    duration: "1:45",
    url: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80",
    gradient: "linear-gradient(135deg, #1f7a4f 0%, #6fa876 100%)",
    fileSize: "38.5 MB",
    resolution: "1080p Full HD",
  },
  {
    id: "m-4",
    title: "Audition Clip - Intense Hindi Crime Monologue",
    type: "Audition Clip",
    date: "2026-09-28",
    status: "Pending",
    duration: "0:58",
    url: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=600&auto=format&fit=crop&q=80",
    gradient: "linear-gradient(135deg, #25502f 0%, #bfe3b4 100%)",
    fileSize: "18.2 MB",
    resolution: "1080p Full HD",
  },
  {
    id: "m-5",
    title: "Full Body - Modern Western Casual Look",
    type: "Full Body",
    date: "2026-09-20",
    status: "Rejected",
    reason: "Image resolution is below the 1080p requirement and the lighting has heavy shadows. Please re-upload with soft front lighting on a plain grey/neutral background.",
    url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=80",
    gradient: "linear-gradient(135deg, #4a6550 0%, #8fbf8a 100%)",
    fileSize: "1.1 MB",
    resolution: "720 x 1080 px",
  },
  {
    id: "m-6",
    title: "Dance & Stage Movement Showreel",
    type: "Showreel",
    date: "2026-09-10",
    status: "Approved",
    duration: "1:15",
    url: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    gradient: "linear-gradient(135deg, #25502f 0%, #6fa876 100%)",
    fileSize: "29.4 MB",
    resolution: "1080p Full HD",
  },
];

export const initialCastingCalls = [
  {
    id: "call-1",
    title: "Mumbai Diaries Season 3 (High-Stakes Medical OTT)",
    production: "Emmay Entertainment & Prime Video",
    category: "OTT",
    city: "Mumbai",
    location: "Goregaon Film City & South Mumbai Hospital",
    budgetLabel: "Paid (₹80,000 - ₹1,20,000 / episode)",
    budgetType: "Paid",
    rolesCount: 2,
    deadline: "2026-10-04", // 3 days away
    daysLeft: 3,
    isUrgent: true,
    featured: true,
    bannerGradient: "linear-gradient(135deg, #25502f 0%, #6fa876 100%)",
    description: "Casting for key recurring supporting characters in the critically acclaimed hospital emergency drama series 'Mumbai Diaries Season 3'. Shoots in Mumbai across November 2026 - January 2027.",
    roles: [
      {
        roleName: "Dr. Tanya Roy (Junior Trauma Surgeon)",
        ageRange: "21 - 27 years",
        gender: "Female",
        look: "Sharp, composed, athletic build, professional look",
        language: "Hindi & English (Fluent)",
        skills: "Medical dialogue delivery, emotional control under stress",
      },
      {
        roleName: "Rohan Varma (Investigative Journalist)",
        ageRange: "24 - 30 years",
        gender: "Male / Any",
        look: "Urban, intense expressions, dynamic screen presence",
        language: "Hindi (Fluent)",
        skills: "Fast-paced conversational dialogue",
      },
    ],
    dates: "Nov 15, 2026 - Jan 20, 2027",
    requiredMaterials: "1 Headshot, 1 Full Body, 1 Dramatic Self-tape monologue",
    eligibility: "Must have verified Vismaya profile. Prior screen acting or theater experience preferred.",
  },
  {
    id: "call-2",
    title: "National Beverage Summer TV Commercial",
    production: "Ogilvy & Mather / Nirvana Films",
    category: "Advertisement",
    city: "Mumbai",
    location: "Studio Shoot, Andheri West, Mumbai",
    budgetLabel: "Paid (₹1,50,000 lump sum + usage)",
    budgetType: "Paid",
    rolesCount: 1,
    deadline: "2026-10-06",
    daysLeft: 5,
    isUrgent: false,
    featured: true,
    bannerGradient: "linear-gradient(135deg, #25502f 0%, #8fbf8a 100%)",
    description: "Leading national soft beverage TV & OTT commercial showcasing refreshing summer moments with friends and family. High energy, bright visuals.",
    roles: [
      {
        roleName: "Lead Female Friend (Protagonist)",
        ageRange: "20 - 25 years",
        gender: "Female",
        look: "Bright expressive smile, radiant skin, youthful collegiate look",
        language: "Hindi",
        skills: "Natural expressions, spontaneous energy, camera ease",
      },
    ],
    dates: "Oct 24 - Oct 26, 2026 (3 Shoot Days)",
    requiredMaterials: "Current commercial headshots, 30-second introduction smile video",
    eligibility: "Open to all verified talents with commercial portfolio.",
  },
  {
    id: "call-3",
    title: "Period Historical Feature Film 'Samrat'",
    production: "Yash Raj Films Collab",
    category: "Film",
    city: "Delhi NCR",
    location: "Heritage Palaces in Jaipur & Delhi",
    budgetLabel: "Paid + Travel & Stay (₹3,00,000)",
    budgetType: "Travel + Stay",
    rolesCount: 3,
    deadline: "2026-10-12",
    daysLeft: 11,
    isUrgent: false,
    featured: true,
    bannerGradient: "linear-gradient(135deg, #1f7a4f 0%, #6fa876 100%)",
    description: "Epic historical drama chronicling 16th-century royal court intrigues. Big-screen theatrical release with a visionary National Award-winning director.",
    roles: [
      {
        roleName: "Priyamvada (Court Classical Dancer & Confidante)",
        ageRange: "20 - 26 years",
        gender: "Female",
        look: "Classical Indian features, graceful posture, expressive eyes",
        language: "Hindi & Urdu diction",
        skills: "Classical dance (Kathak/Odissi mandatory), dramatic dialogue",
      },
      {
        roleName: "Prince Devavrata (Young Rebel Heir)",
        ageRange: "22 - 28 years",
        gender: "Male",
        look: "Warrior physique, intense gaze, martial posture",
        language: "Hindi (Formal)",
        skills: "Sword combat, horse riding",
      },
    ],
    dates: "Dec 01, 2026 - Feb 28, 2027",
    requiredMaterials: "Traditional look headshot, classical dance video clip (1 min)",
    eligibility: "Classical dance proficiency is strictly verified by Admin.",
  },
  {
    id: "call-4",
    title: "Indie Romance Music Video 'Sufiyana'",
    production: "Sony Music India & Desi Melodies",
    category: "Music Video",
    city: "Goa",
    location: "North Goa Beaches & Heritage Portuguese Villas",
    budgetLabel: "Paid (₹60,000 all-inclusive)",
    budgetType: "Paid",
    rolesCount: 1,
    deadline: "2026-10-02", // 1 day away
    daysLeft: 1,
    isUrgent: true,
    featured: false,
    bannerGradient: "linear-gradient(135deg, #25502f 0%, #bfe3b4 100%)",
    description: "Soulful acoustic romantic track sung by a top Bollywood playback singer. Story explores two travelers meeting along the Goan coast.",
    roles: [
      {
        roleName: "Meera (Free-Spirited Traveler)",
        ageRange: "20 - 26 years",
        gender: "Female",
        look: "Bohemian aesthetic, expressive eyes, photogenic close-ups",
        language: "Hindi / Non-verbal emotional acting",
        skills: "Subtle emotive acting, comfortable on beach sets",
      },
    ],
    dates: "Oct 14 - Oct 16, 2026",
    requiredMaterials: "Natural light outdoor photos, aesthetic video snippet",
    eligibility: "Must be available for 3 consecutive shoot days in Goa.",
  },
  {
    id: "call-5",
    title: "Lakme Fashion Guild Showcase 2026",
    production: "IMG Reliance & Fashion Design Council",
    category: "Event",
    city: "Mumbai",
    location: "Jio World Convention Centre, BKC, Mumbai",
    budgetLabel: "Paid (₹40,000 / runway day)",
    budgetType: "Paid",
    rolesCount: 6,
    deadline: "2026-10-08",
    daysLeft: 7,
    isUrgent: false,
    featured: false,
    bannerGradient: "linear-gradient(135deg, #4a6550 0%, #8fbf8a 100%)",
    description: "Premier high-fashion designer showcase featuring couture collections from top Indian couturiers. Runway and digital livestream broadcast.",
    roles: [
      {
        roleName: "Runway & High-Fashion Model",
        ageRange: "18 - 28 years",
        gender: "Female / Male / Non-Binary",
        look: "Minimum height 5'7\" (Female) / 5'11\" (Male), sleek posture",
        language: "English / Hindi",
        skills: "Professional catwalk, comp card poses",
      },
    ],
    dates: "Nov 05 - Nov 08, 2026",
    requiredMaterials: "Full body comp cards, 15-second runway walk video",
    eligibility: "Strict physical height standards per fashion guild guidelines.",
  },
  {
    id: "call-6",
    title: "Crime Mystery Thriller 'Kohrra Season 2'",
    production: "Clean Slate Filmz & Netflix",
    category: "OTT",
    city: "Punjab",
    location: "Chandigarh, Ludhiana & surrounding villages",
    budgetLabel: "Paid (₹90,000 / episode)",
    budgetType: "Paid",
    rolesCount: 2,
    deadline: "2026-10-15",
    daysLeft: 14,
    isUrgent: false,
    featured: false,
    bannerGradient: "linear-gradient(135deg, #25502f 0%, #6fa876 100%)",
    description: "Gritty, critically acclaimed investigative thriller exploring secrets in rural and urban Punjab. Raw, authentic performances needed.",
    roles: [
      {
        roleName: "Gurleen Kaur (Forensic Assistant & Crucial Witness)",
        ageRange: "21 - 27 years",
        gender: "Female",
        look: "Natural realistic look, strong presence without heavy makeup",
        language: "Punjabi (Fluent) & Hindi",
        skills: "Understated acting, intense dialogue delivery",
      },
    ],
    dates: "Dec 10, 2026 - Feb 15, 2027",
    requiredMaterials: "No-makeup headshots, Punjabi monologue clip",
    eligibility: "Fluency in conversational Punjabi is mandatory.",
  },
  {
    id: "call-7",
    title: "Electric SUV Automobile TVC & Digital Campaign",
    production: "Nirvana Films & Tata Motors Collab",
    category: "Advertisement",
    city: "Pune",
    location: "Lonavala Ghats & Studio Pune",
    budgetLabel: "Paid (₹1,20,000 all-inclusive)",
    budgetType: "Paid",
    rolesCount: 2,
    deadline: "2026-10-14",
    daysLeft: 13,
    isUrgent: false,
    featured: false,
    bannerGradient: "linear-gradient(135deg, #1f7a4f 0%, #8fbf8a 100%)",
    description: "Cinematic commercial for a next-gen luxury electric SUV driving across scenic mountain roads and modern cityscape.",
    roles: [
      {
        roleName: "Young Tech Entrepreneur (Lead Driver)",
        ageRange: "23 - 30 years",
        gender: "Female / Male",
        look: "Contemporary urban styling, confident screen charisma",
        language: "English & Hindi",
        skills: "Valid four-wheeler driving license, comfortable with camera rigs",
      },
    ],
    dates: "Nov 02 - Nov 04, 2026",
    requiredMaterials: "Current profile photos, valid driving license copy",
    eligibility: "Active valid Indian driving license required.",
  },
  {
    id: "call-8",
    title: "Bilingual Crossover Feature Film 'Drishti'",
    production: "SVF Entertainment & Hoichoi Collab",
    category: "Film",
    city: "Kolkata",
    location: "North Kolkata Heritage Mansions & Shantiniketan",
    budgetLabel: "Paid + Travel & Stay (₹1,80,000)",
    budgetType: "Travel + Stay",
    rolesCount: 2,
    deadline: "2026-10-20",
    daysLeft: 19,
    isUrgent: false,
    featured: false,
    bannerGradient: "linear-gradient(135deg, #b7791f 0%, #e0a82e 100%)",
    description: "An emotional relationship drama exploring generational conflicts in a prominent intellectual Bengali family.",
    roles: [
      {
        roleName: "Aditi Sen (Aspiring Painter & Granddaughter)",
        ageRange: "19 - 25 years",
        gender: "Female",
        look: "Artistic, expressive, bohemian aesthetic",
        language: "Bengali (Basic/Fluent) & Hindi",
        skills: "Subtle nuanced emotional range",
      },
    ],
    dates: "Jan 05 - Feb 10, 2027",
    requiredMaterials: "Headshots, emotional scene self-tape",
    eligibility: "Actors open to staying in Kolkata during production schedule.",
  },
  {
    id: "call-9",
    title: "Campus Comedy Mini-Series 'Hostel Chronicles'",
    production: "The Viral Fever (TVF)",
    category: "OTT",
    city: "Mumbai",
    location: "Campus Location, Navi Mumbai",
    budgetLabel: "Paid (₹35,000 / episode - 5 episodes)",
    budgetType: "Paid",
    rolesCount: 4,
    deadline: "2026-10-05", // 4 days away
    daysLeft: 4,
    isUrgent: false,
    featured: false,
    bannerGradient: "linear-gradient(135deg, #25502f 0%, #6fa876 100%)",
    description: "Relatable, laugh-out-loud college hostel comedy following engineering students preparing for cultural festival and placement season.",
    roles: [
      {
        roleName: "Akriti (Sarcastic Debate Club President)",
        ageRange: "20 - 24 years",
        gender: "Female",
        look: "Smart, witty, expressive comic timing",
        language: "Hindi & English",
        skills: "Sharp comedic timing, witty punchline delivery",
      },
    ],
    dates: "Nov 12 - Nov 28, 2026",
    requiredMaterials: "Comedic monologue self-tape (under 1 min)",
    eligibility: "Prior comedy or theater improvisation background favored.",
  },
  {
    id: "call-10",
    title: "NFDC Cultural Docu-Drama 'Forgotten Rhythms'",
    production: "National Film Development Corporation (NFDC)",
    category: "Film",
    city: "Hyderabad",
    location: "Telangana & Andhra Rural Art Centers",
    budgetLabel: "Travel + Stay (Honorarium ₹45,000)",
    budgetType: "Travel + Stay",
    rolesCount: 2,
    deadline: "2026-10-22",
    daysLeft: 21,
    isUrgent: false,
    featured: false,
    bannerGradient: "linear-gradient(135deg, #1f7a4f 0%, #bfe3b4 100%)",
    description: "Government-supported documentary feature capturing disappearing traditional folk theater and temple dance forms.",
    roles: [
      {
        roleName: "Young Documentarian / Folk Performer",
        ageRange: "20 - 28 years",
        gender: "Female / Male",
        look: "Natural, grounded Indian persona",
        language: "Telugu / Hindi / English",
        skills: "Voice-over narration, folk or classical rhythm sense",
      },
    ],
    dates: "Jan 15 - Jan 30, 2027",
    requiredMaterials: "Narrative voice clip, artistic bio",
    eligibility: "Open to all verified artists across India.",
  },
  {
    id: "call-11",
    title: "FTII Pune Graduation Short Film 'Kinar'",
    production: "Film and Television Institute of India (FTII)",
    category: "Film",
    city: "Pune",
    location: "FTII Campus & Konkan Coastline",
    budgetLabel: "Unpaid (Festival Credits, Reel & Full Travel)",
    budgetType: "Unpaid",
    rolesCount: 2,
    deadline: "2026-10-07",
    daysLeft: 6,
    isUrgent: false,
    featured: false,
    bannerGradient: "linear-gradient(135deg, #4a6550 0%, #6fa876 100%)",
    description: "High-art cinematic short film screened at international film festivals (Cannes Cinefondation, IFFI). Outstanding portfolio showreel opportunity.",
    roles: [
      {
        roleName: "Shalini (Coastal Marine Biologist)",
        ageRange: "21 - 27 years",
        gender: "Female",
        look: "Thoughtful, introspective, quiet screen charisma",
        language: "Hindi or Marathi",
        skills: "Method acting, quiet emotional intensity",
      },
    ],
    dates: "Nov 01 - Nov 08, 2026",
    requiredMaterials: "Dramatic self-tape clip",
    eligibility: "Actors looking for international festival credits.",
  },
  {
    id: "call-12",
    title: "International Luxury Jewellery Print Campaign",
    production: "JWT Global & Malabar Heritage",
    category: "Advertisement",
    city: "Mumbai",
    location: "Mehboob Studio, Bandra, Mumbai",
    budgetLabel: "Paid (₹2,50,000 lump sum)",
    budgetType: "Paid",
    rolesCount: 2,
    deadline: "2026-10-04", // 3 days away
    daysLeft: 3,
    isUrgent: true,
    featured: true,
    bannerGradient: "linear-gradient(135deg, #25502f 0%, #e0a82e 100%)",
    description: "High-end luxury gold & diamond heritage jewellery print catalog, hoardings, and digital magazines across India and Middle East.",
    roles: [
      {
        roleName: "Royal Heritage Bride Look",
        ageRange: "20 - 26 years",
        gender: "Female",
        look: "Classic royal Indian features, graceful neck profile, photogenic hands",
        language: "N/A (Print / Digital)",
        skills: "High fashion editorial posing, close-up expressions",
      },
    ],
    dates: "Oct 28 - Oct 30, 2026",
    requiredMaterials: "Close-up beauty headshots, hand profile photos",
    eligibility: "Must have verified high-resolution portfolio on Vismaya.",
  },
];

export const initialApplications = [
  {
    id: "app-101",
    callId: "call-1",
    projectTitle: "Mumbai Diaries Season 3 (High-Stakes Medical OTT)",
    roleName: "Dr. Tanya Roy (Junior Trauma Surgeon)",
    category: "OTT",
    city: "Mumbai",
    appliedDate: "2026-09-27",
    status: "Shortlisted", // Applied, Under Review, Shortlisted, Not Selected
    stage: 3, // 1: Applied, 2: Under Review, 3: Shortlisted, 4: Audition Scheduled
    adminNote: "Admin Feedback: Self-tape monologue scored 9.4/10. Excellent emotional control and medical jargon flow. Vismaya Casting Executive will coordinate the virtual callback slot.",
    submittedClipName: "Dr-Tanya-Trauma-Monologue.mp4",
    applicantNote: "I have prepared the medical monologue and have previous experience in realistic emergency scenes.",
    timeline: [
      { step: "Application Submitted", date: "27 Sep 2026, 02:15 PM", done: true },
      { step: "Admin Verification & Screen Test Review", date: "28 Sep 2026, 11:30 AM", done: true },
      { step: "Shortlisted for Production Audition", date: "29 Sep 2026, 04:45 PM", done: true },
      { step: "Audition Slot Coordination", date: "Pending Schedule (Oct 3)", done: false },
    ],
  },
  {
    id: "app-102",
    callId: "call-2",
    projectTitle: "National Beverage Summer TV Commercial",
    roleName: "Lead Female Friend (Protagonist)",
    category: "Advertisement",
    city: "Mumbai",
    appliedDate: "2026-09-24",
    status: "Under Review",
    stage: 2,
    adminNote: "Admin is reviewing submitted commercial smile reel and checking schedule compatibility with client shoot dates.",
    submittedClipName: "Summer-Beverage-Introduction.mp4",
    applicantNote: "Available for all 3 shoot days in Mumbai. Active passport and commercial experience ready.",
    timeline: [
      { step: "Application Submitted", date: "24 Sep 2026, 10:00 AM", done: true },
      { step: "Admin Review in Progress", date: "25 Sep 2026, 03:00 PM", done: true },
      { step: "Shortlist Announcement", date: "Expected by Oct 05", done: false },
      { step: "Client Audition Call", date: "TBA", done: false },
    ],
  },
  {
    id: "app-103",
    callId: "call-4",
    projectTitle: "Indie Romance Music Video 'Sufiyana'",
    roleName: "Meera (Free-Spirited Traveler)",
    category: "Music Video",
    city: "Goa",
    appliedDate: "2026-09-20",
    status: "Applied",
    stage: 1,
    adminNote: "Application received and queued for Admin assessment.",
    submittedClipName: "Acoustic-Emotive-SelfTape.mp4",
    applicantNote: "Huge admirer of the singer's discography. Open to traveling to Goa immediately.",
    timeline: [
      { step: "Application Submitted", date: "20 Sep 2026, 06:20 PM", done: true },
      { step: "Admin Review", date: "In Queue", done: false },
      { step: "Shortlisting", date: "Pending", done: false },
      { step: "Audition / Lock", date: "Pending", done: false },
    ],
  },
  {
    id: "app-104",
    callId: "call-7",
    projectTitle: "Electric SUV Automobile TVC & Digital Campaign",
    roleName: "Young Tech Entrepreneur (Lead Driver)",
    category: "Advertisement",
    city: "Pune",
    appliedDate: "2026-09-12",
    status: "Not Selected",
    stage: 2,
    adminNote: "Thank you for applying. For this campaign, the production team required an actor with 5+ years of off-road driving certification. We look forward to seeing your application for upcoming fashion and lifestyle TVCs!",
    submittedClipName: "Car-Commercial-Look.mp4",
    applicantNote: "Driving license attached in portfolio.",
    timeline: [
      { step: "Application Submitted", date: "12 Sep 2026, 11:10 AM", done: true },
      { step: "Admin Assessment", date: "14 Sep 2026, 02:40 PM", done: true },
      { step: "Decision Finalized", date: "16 Sep 2026, 05:00 PM", done: true },
    ],
  },
];

export const initialNotifications = [
  {
    id: "notif-1",
    title: "You were Shortlisted for Mumbai Diaries S3!",
    message: "Admin has shortlisted your application for 'Dr. Tanya Roy'. Vismaya casting team will coordinate your callback audition details.",
    type: "Applications",
    time: "2 hours ago",
    read: false,
    actionHref: "/talent/applications",
    icon: "CheckCircle2",
    badge: "Shortlist",
  },
  {
    id: "notif-2",
    title: "Audition Alert: 3 Nov, 11:00 AM, Andheri Studio",
    message: "In-person audition slot assigned for 'Historical Feature Film'. Please arrive 15 minutes early in requested traditional attire.",
    type: "Audition Alerts",
    time: "1 day ago",
    read: false,
    actionHref: "/talent/applications",
    icon: "Calendar",
    badge: "Audition",
  },
  {
    id: "notif-3",
    title: "Your Showreel was Approved",
    message: "Your media upload 'Dramatic Monologue Showreel (2026 Edition)' has passed moderation checks and is now active on your public talent comp card.",
    type: "Announcements",
    time: "2 days ago",
    read: false,
    actionHref: "/talent/portfolio",
    icon: "ShieldCheck",
    badge: "Verified",
  },
  {
    id: "notif-4",
    title: "Admin Announcement: 5 New Casting Calls for Mumbai Actors",
    message: "New verified high-budget opportunities for OTT web series, TV advertisements, and feature films were posted today.",
    type: "Announcements",
    time: "3 days ago",
    read: true,
    actionHref: "/talent/casting-calls",
    icon: "Megaphone",
    badge: "New Calls",
  },
  {
    id: "notif-5",
    title: "Application Received: Beverage Summer Commercial",
    message: "Your submission has been queued for Vismaya Admin screening. You will receive an update once reviewed.",
    type: "Applications",
    time: "5 days ago",
    read: true,
    actionHref: "/talent/applications",
    icon: "FileText",
    badge: "Received",
  },
];
